---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-initial-admin-secret
  namespace: ci
spec:
  encryptedData:
    password: AgBBRcITU+94ggUQ01NvYTTnZwt7sacfZ2JGvuiXzIhJA4Nf04qMDokzU9fQbUZpBBtV6A+nK0eALhmH4JlKA2DyUgBCm0DTLaW8S+aKTruE8cyvuxxWW8HyKnpjAzYyRxNQk3dF5B67x4s0ZYMqfFvCouIwNQ77Y8vcPvqphmX1yZgrYNzbP1mi+7GAcvBbS2cscYp060n5K3lkh8mk2pz7I4HWN5RtFztMolqimXCUO22jYa/abnKkQNu/KtQiyonZJrsefzowLURi0ZFRrEU0mtNH852Z7Va2px6NHgolj7GgY3cRDPQ9MS0ME+YTWk70ocKw2+epYEPqXeRJ58TdepYYHvM8x946aCwRmTu4lltQ0XM2v2QXjjp3g9mlMN2Fguh5nUJD21zv8gWq1OVRvCWuaVh6oXXyq+wGvQQP+LRzM0SqvotZbduktgiWynBu5whjSvF/L+BKYUsB5/kDv1WcH2CS1KGeZq0QlTE5khnstaqKHbCF9i1CVmUg40qC10+c/bx3eG0RMIy9Su5vklhJCFXIQ/xCllvtKcLyLkBYSkn1AZN9AX7u1MAi4tcWqWoNAgmFoq5ukGUs9sQlK4ktFit6zehyw3AuF7965k+ksrL0pqWLVOpt4rfRZXHmEL5lBK4x3bU+Li/R/uVYbHEnQ7XY8Z7G4O7eguoiQiDDdPragZKdS1IgsqL0yKhmQZPcECgpJZWu48xqiPU9
  template:
    metadata:
      creationTimestamp: null
      name: argocd-initial-admin-secret
      namespace: ci
    type: Opaque
