---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-initial-admin-secret
  namespace: ci
spec:
  encryptedData:
    password: AgBqkuNZAAnZNpbdUOFky38R6qmF4z3HSCeVw+pPd4A94hhMZ+2zVsI9cIgQwnmSLj9DJIGVW6USipulF6RP743RO8qTBX7ycfy7e/6jfp6rd4zHdTD5gcLN05RIpqmBDQvQAuDPCKUtUpFkhYUrB7gbHWOfw165I0cdZzpuHYoFSX0E4GZZX/FyNZ3oztnD1i8S0sUEfxeqhaV9Jx9lw7/36mKRVhxUbLrPEQY6ti9G1Ssla05UKuV3NjCEujCVJQAIWBOKNDM28HPaR3kk5dhlA5zYEkIXJHYUEEJJyM9bAPe44urcdIYNXSbkZXnyLF6FnhUyzW1E025FJtOGAMcup2MxsZ2fkx1pcZ8FLgEPX2nlWo5D/mVZp5hRf8hhL5GEJTDUkKmmh9odDkJGVnR4aF9fWG9oG/J8jIL8twwe9B4miuna+CFgZJqVj4SseU7/0T2nuZZmxqKb+QZJ8O4+G3LNiKlkzh3N9Io9unwNtn/jJKkEDKvfWJ9t8Lm4PmmTl1KRlCHRYK4j+FfMWjDIg03IHLEY8D45pLT6APtSQ/q9ufLQUqqT4Q4oTkgSw0OA9SwXVglaj57N3xCmZO3Yq70A7LUyuH3FWxAHtC7b/vvfm8XKgeDdIEAZe5EqBCpId8ybiEOIV2u5UvC6CIVBsUX9py2T2Cob/VhsZtZ1OGl3F39gSpntik34Bj4Yovgr6GkRPUrC09awY4NATpHl
  template:
    metadata:
      creationTimestamp: null
      name: argocd-initial-admin-secret
      namespace: ci
    type: Opaque
