---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-initial-admin-secret
  namespace: ci
spec:
  encryptedData:
    password: AgCUzwGsIUVJbaL/9IfQk4Ba7IL4tfDtKGqUxOZYuj2Y6LvDWkSLOskdf5LCEjaaaWeyVIgPmvdBWb4zqy+bugKrcHA9WI7msSLENA4ht8UTJwiOdNmMi+eVY8Iq724qZeUgbyBGrO+EyoEb6ZOyrKYDma9i84QL41/xV/Vx0bVH65k9OuyeBlWsySPWrSl1Di2Z4Y7Ry3ufUUMC6FmZanxU4nvR68WH6DmMG6jlHNESiIL7K7T2oHIknsdpvzaS8n3agacA55AKLrt7cAgcADP8ZYceYjdQZmGn5awtC4/2JGzHSHAM/mkJM5cpfzW1XOIkC8+q7Ul0rshzQRRRvq0qn61zOALHgtuwUIx/l4By4LfQyfWQ29jXPPTR3KJ7ysiR+R8/E1+23bkBeXApRmLTGJa8/ZW7SuZTl0/zJp3HRBy+aisI/X4Pm1hHqwIt+hgyfrYmdC/pJ7IC/APs4CnKap0a9+7YpZJ6i7o9aqceQicoNyoEeL1InfouCh6Il7A5jcW1pGjRTB+idJOwSaHeY3pJ4wBUwcUKoz5N0UX38xuzRzQm2d6btc6NDbIr39MjBRSpd9qa/ixsHd4ABHqXnftQTMWpjdQq53HS0389oWr7NRQLSrEU718dlssUw298fV8UsEL0OLCjXABxArEQuv+LV28lPssXhYG6WtimxAUF+DJE9NUA81myaWdWSBwvkcDLemSWpzpdmRURWVXZ
  template:
    metadata:
      creationTimestamp: null
      name: argocd-initial-admin-secret
      namespace: ci
    type: Opaque
