---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAdHmg24fJvq1mw+RwAs/wH8pvhK0+r+CJehG8BT2vyAIKyxdx5mohNCjQ/bQyAqB4lMRDy0a4vxog8E6ga0nkQyGhkFWQLXp0Ohl6LL9tUiWkMLwjIc7RR+LGzmWLpu9F6VP2pg0koNI7EVp5X/Aliaba8LAA0Hofy3gqqi3FV5vtms7fwygfPw75LJDb5JXoee2Uds15nA5XON4FKDuooi+oeaRACK0om1Jwb0FaiUMxS9n8JatAcuhrmE1fb0R8JLvegppy+0Y1KEocECdIy5/T5VCxBw2SxgPznL4jWf6lbuBLde1sg7r6ReRddGrO0J3rEk5TDw2pKyBzYp7CdfR1E4gqkVOhrl58AEEDCKHd/A8BH50AkJr421lmwpn06tbyibHD9FvXTy4kq3A+AgNACvvSOXp22bDydKD2sAakfZp+UgbMqSJNwlPLaSDE3ixM3ixN54nDelCFdTieCwz2CFQ+oa3qFF9hZKl8ItVEjGXy8oX0zXKmjExaIPC00SaJZkgBEeUYODM7lv4Jsdix4la3Xb+yAefzgE7fKBU7/DAR9ZF2euoJZzpfDIdk2ljhny9jRIYUMHDFbT/CgBzqAKurKtxgXX5M23JCaPmIQElypvcploNytOF84+S8gPL3mtWPSVcbssA29YqjO07lcQ4xWalxsC909in1YldGaV/+CrXbAOUHItlqgTntKhBcHJ+u+FyU=
    username: AgBzo1bgAo39ArzXdh86kGAI+RdYcxww3HN050HY0uFtUK+WNskq4jYFLL8gD8vis/egWm9e9LAC8qM+PHngI6Bv9YcmfRKVJRb9//sy/PXJOuHxbcrJF2BVKlDaHTm61/swkWqpcD5ZbsJXBKQlum2c/B7bJBsQITcdQi8yDEKNTHg52Wjguck46cOde4ITVdp+tw+vIYJ1/GhQlidWepjoKH5dKFL35Vs1eudfR4LTmW52UjrIlEvzP1Q+GoaxYwkEaqBIxHpsRj7srEM0s3SL8rT1nkYHuVCAr0MLPyOmGoq71V5gOENAQLw9AjKCrVln7uHm8Jo1Vvz/qbHIS/x/hY15Asawh2JiWgP1DrBoR16pa0xh3sbi8V2NraSDu6WZCKT4ipXyPuVr2mJkGyRNAwjqxx2MCMZb+Wuz9vmNsA7lgEMi2Zg+WBy9fnzMvcpyHyURicIRXtoqFdAjPdFwcSKACuHa0BIvqQ5AVlctkqgb+3boCL2VR9o+AhzG9uVd5uXUbqsZQnODzwrMQvMZAyy7Rp84gEl6iJDJeTMkajMykvJFueBv3In/ZTdb3Wxg76ehYufW4xIKNadJOny/2J651M766G0YAiLWhoumlpALsoRcrw1VPbf5qlytydKngIpoMjP3x0yxGdEaPTl8iFuB3AazqLYG2eI0jgqMC4jlLBnuo7pyXy1F+FfcSeRVRQsBrA==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
