---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgC4UfkY5EPFXkab53cT7rlZCIJP4yvjBWZ/u7DE+5f+1EpI1GfZfcG5Q09EC1XqxmJW6ByV0lgD3aCCrnQUjYfeSWqCq7D0/Tm4BvFLcWwPGthqAJSjHOPJcmVaN3iCsFMZWNBLJgAcIcN8f9m47sVxJt+uj7+PFjSwDCalNjHSQDKmF4Kzb4OhRER6+sShyNib5Rdp2/rhIwOq7B+ulb6y0oBkS+5iy+A1Z8m6QA61Z8aVEZrHXSgUhM/dCCZI0ex24Sc4q5tPG54EeSyDxGZnsWPX+6UKredZJfPgeMfQNXtlVZDv1WJkSXF5d0O/TKiV27H3WzdiTtd/S59Ch9BevEfHIzrbLdiTmKeMBGO+KpFqyxw07OJpPVF2zl84fjR/FqQYEv4qeVbrXqWbDn73FfgsscT8LgsFjTpZjMDuMGXuUeDFCG9xlFZVnQ4TFil5Sxkmcsb9KxeuY77W8slyPy6ZeI8AqRaqlZhthy5KQjqTbfdA6czQnFW4X3jqs/ECtyvwbYRh+LCuokYhH57TABuYloQJ2RpX7WhxPnL/XRRqfyiNoNdyJTm3uiIdhKop7ewoJqMNBLhBptsqQpscKttUK2AChtPmVMqwaFU/oj81gGmm6L92Qg75Gev5UUcyw/rNK28dhbIJu/wzY7/ep9xNTOpAOjVnyhO49vZ7l6/h6roraMccCvFXGjgqv6qPZQ5oM6z6P9c=
    username: AgB9bNFa7C1sxiNk3jmuDFLQ1ImNBxdF+nBWon9Z6f55NUHQuNVLy01fMFY/bU78QKzO4tp9qkTvTsdACpT3YmVp5wr9aOLCLf/nzzPUZjRCCcjjL66Y3uJxVrLGtq6Bb69PI5rwvnHMdODiBRNjpfZfXR0PHbIdBADhNo52CvxeCDWSRufYzi09FOqNiMqw5Z++8TUZWLNmqh9t1GKkV6ON/gkVNIj2QmsmWM4cURZBtWaSUt4zLxCfZ9GKLoz1/bzEIs0/8Hqe9SSRg3dfEqeeU0bfoIFS+4ewP2zs+fK7xCNL/34jJFlpV8ZZL7t8bmj++F7qMkUXoxIfZrcggQi7HKgClP3d84TrvccT4atOUFYv0GrcoidCi+VirOQO7GTFWgpk0BFJuDwW9Xqou82j+q2Eph1Ibbd7CP0oS7051VANx2eZ5qe3sitvqdbLzmBh0ko1UcQH45ZyaBwJM7JZy5MLbkHQezeozNBih68KxZSERkIOJivtmh/l5N0xcaCrJ49UMRL7M3PMKkjD+dYzxLKOdmTNcBmY0/m0arAmV6hfyIMgp+5h/hgPeg+e/kgOl3C6oMgzUAy2cC3imceA5ZuxWprAokr9DBoOmn3PwHXxg+rp0zu6tua1rTjCEEZmGBuvkr/cTZOHIflOwX/TKYLvOD3KQ3f/UwFYgAqShT9sHi0muUPsX1IWSUcEvA0ZQ1EzNQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev-mkoplinger
      name: gitcred
      namespace: ci
