---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAMiiYc3KJxvao0DCA/TK6tLpFShs5/kIVX50IMd/aDUdACQT2FylUlCNk2gjqY14keaV7U+TDszRspy4LHWqXR6YrshNqKOtyEqiGTaTkXMeHzxOrPwe40L36CNqZeko3qaFckXomCdrrT0U6eiIehdml77Le9pcpbyI1LCiNDqCRlmWIrLJe39KNufWiG+02FhaQ9T182FKCbf33rmZFbVL7rFTnqWBQ02hRolhJEufoTaomUR/TsyaWs8kiYwZPScPI9ereCVgIQNN+x3DN7UET0dwVRiwEC+lXrggoFf3b6UpEr4+pmtHEhrdKunArQDvc5oGEr3h5chY3Qc4weq8CSbSEFkeqDvea5fFU1YqxgYCGjzLFdK/YJ6fGaz3cEOTwbFNZG+gVtfMCrTzBL7DRPImx87fh53sgjB6D7hNjS9OiTNEQ5Q0nQTKFU69v6dzMyNUdwvDIEYjaHi9dE5YdifbrT9vTkdtjXVCNNsbsJj8WSqd0fRhv5vb4yUVoPB+HPpKH6PTPD2YDyBj0k69lNizqCIeDvYLIhEczNvSeExKAOTEUi/16s6Ur1UoL9akUehbO6OYu4nNoryblk2a6ECPCWxRhz5t853ziB9Ee0AQnaXhmasiq81HCF4huvtOEq+GBeYFeYH6xdutwYTvuEUfhLk0GsH8ua28drwN/eTUcepO9DtdB7LEMAsLjQEUjuzZC7ekI=
    username: AgA8vIrms6o9TJSkct6CX8Fdn6jkdfnz9ZodRK3g1ElfV/0rYER1qZPQudLzDw3M17HBC/PNPWl6BLiJs2zk/q/0w9Hw/NzS7v4J6OqrvWsacWHVHkbaLDoQLkdcA6TUKLwFax9vc+G9397110dIgQqzg/FEuCxF41PbU1+6/SOncBSia3cb+bs4UJMCDOGV9D9EjPX1PL/jSNsIJJZHfLtiB1SdXTM2roBSHGWhbPu65+0lCywzN1mRSKewXsi4BtVc25h/7qG22nFGftxuEndTbJAMi/9nzQw9cS6tYXyUlkf/mSDCxkIDPmNR+mEYMOLmu6PZKSWiw+4WUUF2FbOvGF1w+M0jUnqzpJnqYNDdaSbuKDwPMPJM6O8SFk684TT+UTIvkX7f6t1NtsLf/gIWf+J4r4Ko+5+uupONJfQNl6aIgphniF+n7hRuPbPVlw8xEpT9bpbov0NsY2+Q2aeCuQQzSHLDUmUqfitun42B8a2j1d/KhJA5s3NXqyKOREa94JO7RH5y50gvLFW+lEy03qOuB9s7JP3ifWgH0Hi04kI5KiQFuxvHOeQM6+PqcYNk1195ceCKNiJ+/6ArQKen1+9ia/aKWgcVvQbZ3OmK8yIWfBKWf7/DAK8jwqY/wACDFmJNdrkSszw+DYTlQDp4DIb/kmvR3K59oDnel1otaCWBlpbbimw1y+puUL9Xj9ujVhjh2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev
      name: gitcred
      namespace: ci
