---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAbqaN8zIVuOMcWJKoupe5rQt75n340webzekEbYdLM7sSDLLFe+3Sqy3b/HTXDk3TM4BryXH0ZUvWdndfMsn5IJtBAHzhAVSClq/O6CocMGuF1niuHnhceV/9/3GU+xyoDAUgqq03gnUhICbKQ5mYbzA0PAUcdhFn9F7M6TANShMRA4K3PtbzQvnB8G9H2HQal9vmtHCYpD9kvhTgt5BFrNmpXSHoSf9qw6hL+WYPQSUEGA8UbegVGcq6qkrDKgnjb10xuV+doqPIbLefj+HctwFtfUTo0F/fCxCIA/7tI/UGwXmaya1iD+v1CkalUXCJn7o6eY83gYcOU3vnlBt/NgG/czZxm511q8E7IykUcRM+mNaILbfvNwpxusG1QAyjAlxoEqulmFTpTSvRNudHXH6jlT7dQ8lvAaD9vVJ362CijE1MCl8Hx+Y/W5ceOrgl1dT+6u6wK4ZXf40XcQknQLYkZlaKPjkkXfL1AEAmdJI2PYq5RubzCOacNNlna3LTF63BLE6fXyCg17VIbyV3GeneI0QgALdyEjD/AUWRnqz0iT2OHNHZ8xUJeT4JkXBfPXocnLHSBvQhlI2aZ2pjw92q0F+ftmDjoqaCLHjOx6bIB47CCMMTwah8mz1rgCnx0Lthti0dk90aXlRxV9XoiPXnxWkM24hn+jp3bZSNaZ7s8yphAnXquxbazUzC2Syd/2snAPEfrKjk=
    username: AgAyjd9XRQw+e5JmPsjTlioS7ue7SURsgy7q7egjDc188F/uJ9ZRHadniPLKXmzCLTmPbwHymFavaqi2VFpeuRTG1O732M1rX6tu2KJCK5fsJ1+pKLLzgjSW3N/hxHQagZtlWT/41I7WKy/2q323nO6Qr2rOhTrsvZM8onwqtxrmlDokFwH/YTllk5RnRIaEtBGhmqBDFZMR/1rwszIzxWrf4KjY7EprUnF7wTfvLxi4Zuu8Ray0tdbFn/DI8ATuf81UuftY1t6/2k00xRLkFkZu8nqBWbwnLUdtI1qSkl/N037vj7gejLZvxxeJJin+kgQ6RI4/nDxBakAdldhDLW0hgjaIiK57mspi+FhAM+wY+dKoQ9aVRPGqgEwH/QLhgRxmfeBW6haszLTykwVQvOpq0/LHQdFU23hK7fOGJwKx7EyvmblixSyNZHqpmkSnsGNZOFii3s3WJyC4yMqSsxnMjMRh1HoBI3LXiMK09QcW7RtdhN3dIAteVZVLHlMCsdXhtH/63rf5zyWxS+CboH7ji1IEzGeSZdRzLnR9CQKlBJ//ooUvTawZ7pUEZncsLNk1VLWOd2rtfmBZDt6iRUL3fhOcEesLFT+03sWMYlH+ZgaUn1OFyb1mFUojFlvyvkhvlgPdiqvmu/cZ/GQ134IuftbvwE307GUtF/DPiOhsFuFZXmhQRuUz8I/OrUyqoJS0XxMnmQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
