---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAK0KJdUQVgSjbdmvmshixWk/w66JzSPZGvnz71EYhw8oaWOHnhgVKafwq0z1QfaoTOJXBCrkFoRzdHlG0HvzxY0Cv+y8WS6dVbsFgM5VkLoyyhzOqkUvrZW3YyM2PNXt4YJKx7rkpceqCmnSbqe1WogMeZQtEWzpjvs1emzp3ipsvR5Nhr8WVAWZaqbMse09CxSwOVFimu6iba508mxTBXs/a9Mfkc9dSWvb72RqHF4KLOKAtF69npivFfIN17f4jqXPJwuK5zMNVducN7OC96DJolAgXa+LEALiZUBznvR8O5Uut5ia+W/UiMyw5obvW6tJZJ3RRf98AF8BmNDAOFLEOaO34cvMBipS/Ac0a7BawfQjUgZf4tkkaIQj4upNVXSfnyx+YuAo1y8ZR/PPzOm5RBAJ6jOKiDPx1enZuWgbBVhUhn6MJRqCzZ07Z9oZyRsVzhc7Pg8w5j63OLf14FIPwJlUiwKhBuWiRsOC/KQtAkXvqwA4lK/y/3QfdR0ROoRpnBKQytnht/eKgBtTwh7Y0OXI3EFyVn4XCzMXTr+1pU/iCcYMXH0t4yrFdWABpqjKBUHe7JcPr3nhIbcEJVH1oIQrdHj+bWyhJ6EJwmCK0KA8fbcC1KSwWnGY51IeQAJs1EX6fjqwe642mM8juwOHyZwYJitTYWYvdmUSVd+MOQcUVMOE4ZHDeAIyyNOCQ=
    username: AgBgPJTGBOioBBqihglQUTw/P5k6rvCVnseV7yjCFTP4WLbioIO2hAHD0u3Oy69dcvNzzhaBPLuOLFEHqRjIJxP5pYKdjHXn86iNAe6poBwUUXZXqeFEx+vojYE0MdTc7imHt0b9fvorXOocboAmyHU/VwR3Fnh1dlxXOXI4VgqXYQO8+s9nXvsCK2+fuvEXi2d8JdTeOgIkAWVmW7Fx6voNXp2W4mUg0UfPx/GkZg22pi7+NMhfb1PKbFy4Bg/APZH4pSuaVIfXvN0fQLptmJ3cCHqqlsA8bjS+WJGrVwL3JpviKE4f7sfCvP+uWnDCeERwkxYrbqZg5V2BtjOWckrvvQfF8yaOt1Seinv0wJH/JqyfrEcMjAM/I72++no3j9IPEpqZWBaWhfJerkeDqDTXGaSnJn8xyMj9/QUy+9xuiSwRLP8WkHlnOATRk7+ZsS/UNPR13hUuFEl33xXM6LuR6y+MdCKS3xGSMutpkJkDrV7kgXijXVlsyYcmfZHJ56yrSr3B1GDWGK8x0J3KHJfgkbIO2RPRaST0nMo/8fMpOImWnrxNy9DS9wBrtxnLcnGuS6gxJx2TWohC+ptGUTkmeygR6iI8KSDwlxh4oZov+O9RHd2zW9julyoXQg6bl42vaARCtDM6ctXGMAKerxwif0lgU5Z508GQ4KiHhPkXPwfZWN3BNRt3ofdBqByKo9k5lALojA==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
