---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgBhPdJG7Josw/fBxTDU5pM0OO9EHd+BuHajhmyVU7FbvB47v48CLMm4x3uJMznHAexoWdRq3yJlCN7NImUyPfdJFhuftaI7fgBYhKhHhRBmzJKGeexJLtdmZndHxfREVpPPYlO/kwUtrfxczWLfPqfQ4FNWYaX0rI7sk42AbO2Zb8/Remo/V8I/nKoTgPAhP7gtpqQsDLqj7XZCSkEtvLhv/9r5lZOPiSyOuEQjvmHtmCszOb61ijha6xjKstCCeBmLxGzFUokofKaK0IV9348jKJZgzUvI91Mmr1M/JxnEaUdBasmIwcyQ+Ms+jAj5kd+xgBH2lkVY1Q5UwhSof/KVD9cBiVpP6L4OqnVrJ188gBxT8j8RGUxywBDFjkiRwcJO0kU3rs+/IHmqI6QIOoa9zgSHKfnelU0fdXwri3yVqyF51g6m3XdKp1v40Ha9y5VjdMxam7/tEnOK/E2EUcK0lgqw4FnSgJa47dt5P0NxqCECm3vPlNLzkA6zSj6EjkdoMkqyG85WrTBkaFYTetesdFc0lJ982Uxjj0Z7ZqCMxpL9g+u0i4jFHjWF20wpXpI6C3B3Oeo1kacMjyGd91PnAZCmo8XKI0ZJlpOEaNfT64EU28ahk+XSHsZTNzEpCBVOtoB5UdX8Tdy7pYnX+gwGPFRG0zN30DgXZKp6QezpWIFCn0PRMAOe4V/y5Ta2+d/Cm3C3QwtzOlE=
    username: AgBmqPtRQwiN0GicELqM379Oil0C1pcoAtw0qwLSKmnwj89u8og3FQXrmGpSDsH9ReJPVx4G/0mSoOGafaRprS3+6cFaq/2zxtLhFNzMYQZGleiM86R3sxip+dqkeD5GejS0HUn7wNh1Qztkz05O8lBzpZ5ZY5kTpkBTc7QDKVAJ09gqg3ZfikDRE3PzC7NojErpF89/+IN5XvNOCEnzJ/he1wJN7HaPXZczb8Fo48F+b8UmFWrbGuCsKVVG+yPpsDc63W7s/4IPFetlHhF/o48eP6IUQK3QYorDtIeNgo5huaIJQhY+nAlrlj797ZbD/XZHSviHWTXnQ+gUQc7My8BO3Iaim9b+keHUn2VTJIAj0dAlakB+NxTRkzOPYZH705/bHvVhkPYOUaGrF6fxCtbBW8BZS71W5hT+mNqZueqU+N/tK04Nzo6GVJbtRnskX4qqtAdGElooNlDtZiOi3YtR5fz9171eEj9N74bA9tghVEYLKSJ65wyZOIta5qboHuwsGkN+PExDNG8fVJ8EOmG4c6w2ZoZVGm7PMokU3tC3iwN9xvxLMJGsH8ONcM2gmAJ7IuRiRtbDFbOcBJm2psSsdMLNeoyJKpVNno+gxN9vCPyCs+LFm7BvEv/s8BVRdmwi6AtaJJSsSMCTAyJOKuzmhR+TtTvuKMz5HJAJtLD63YtWBdx++W9SlTKgRzTG2DDR2DblFg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: gitcred
      namespace: ci
