---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgBXr+tlQtsQ1hlseKHp4FPKH2Iyzrrb/+L+CHGnInbH9JDIDQ/XZHsfYjSSpBCjUTJp0WhG0dttB0/Au1E+aF4Drrsv7JF2yWFBxdMJGSVMoZsBZJYX0HEzl088/T+vl0XECP9sjSFi5asLhxwdYkMeBGNht9Y1kduegbXvMUFHL+xNTlfe/nobgNcIyPOplnUIw8Tobqc9k2NpeCIpRy9SSJUg4NiN99TF7aQqQoUTmj2yjQfzZi62NlQCFIq1vIp3QXzpcaFbm2HlpCooAZrUxs6p9iJzV6DmrSP+6gRgQmSfi0eW2d+O68BoIhYO4INB9RApUE8eKtZBT4XAFHG8FM+xUWUw07p6TFNfdoZ1h+Mm119qWkrSzI0XgAOM+WBaZ3RkC2y0QRLM7Pn3m/i8WIZArHNPEXK8we7MKYMHR8O0K2uIy0xAfHR2/erXB5LPXnHo/DXDn6zpjvT8UorGHpJKNqs1dCTjNgfwbCKWSIfHkQkWBJuhhlEKLGL24TRbeYViBRYd6cVAJRLbpPs6BPnQ9Tcio5nYZoKWAvsWzlqdNnq551Cbv3DoIjU0LDyx5ztAeKyJMAD9e6TCPh1eYNYk1W8x6ljLmWZcpY03hTW8mbxVQ27tqnhLlSnPU/yKQVOGrJVsC4R8fKcBho2bI1vr0+49k5nlMX6VapXyRyZDrYo+UqglK9kHEPVgZLMhNpHlJxXf72c=
    username: AgCLdVDxQW1BYBOBPkqmb7L5r1kLGezz9dbu9eocemCfprLK27FWIgA6o1kmRfwi+mRRzFT/zN+j8sxlX2bJ+2d9qIkWT9brKt0pyQtjsqcfq7Hf+1z6881C4o+8Ck0zO9T75HuFK5DrNuAy76qqq6BK99AWtoJJf/7MBJWwuHiZ0R1gD6RemaKjF7tNnO8OTSflK96+1Ud3GOonexC/+e7K9ZYS93hOIb+fbkJTD6hpaMwbHqrHKh99ntkz+GxbnXEqXVs3XAgBz9SN3Tgj9X+z4OSm9o0BN0LZmtkw8LhDAcMNaK5DN1G4BjjBoDiG/U6ZpdZrOVuMcdKS6gWpdxtPVsprSLygOjOpjUIn1VQtxCPqHxqDyIYCXobOzevcYD+cGKQxEMbQbk4bWGFXIG6JvoOz0MJetp8tzBSRXChGETavj7hULDcQlTwDWaN0XG008hel6EAbe7WFoMbUqfc785RsYUb5WB5kPWfrtytNUVD5HeqqvzZCumkfkR3z+ACWVd0TYVstkKxgXwdxnh/FKcYDQJsaCLStrn4qRp8gB6wxdDmQINPk9eKAM36yCz1bWJRmeOAkInQj02WGLyntHC3k1F54Z0+V4L5FU6gmsiKIl4i/ehSbRird+s0UZJUt3UP3R03NL5rxe2L+qW9dICTBHtuwaakOMkIUBXTw474U9po5wN5rnozS3SBxrhx83TYZRQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
