---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgBss2sy7iTjuHqGp2Y5jYHI2hcwoX0XeU+Pt5xdjDk22iP/EnsKfU9LNnoYxEimeZCjId0Y24+NIX6Kgos4Hkavg9Xp3qvzMvkUEGJewsJCC1oBbkz7jaApQJsjK2x1ReQaaeXCUhguZYInSdNR3acY8Wrhli/4JYKr6nhHKthGxU3oY4a1mya2b6U6EmqhUsT00QLTe8VS/MHAKrTTxuUf82T6ang9q/Isdvz2eiReoZTyaNZOqxqq7le2zqzDMInjIJR3FfdBJGwMDqtlvxC8f0kI9LlTRscWx1zKMiDydDlaIYUO18uKDhDPRbtJLwe6y8OC/2c7IOwPZLIvw8uyS3ucQjQD/vrujkLCsAKPEmLOu/zgftuvX5EOte2OGS67wsFKOevGKWMkBElWdJAHNhp/9JGUqx+hswn4xiy5z/jhbxVgQD+qC0Sqe3Mp1q/oUWIQ8KpXtRENNEIekCyD2DE0jBmfcqUT5szEbHuQtWA81QGSdIPNmzL+0Ol154yeGPQXA588x89dU/5mNCjr6VXmE/OY2XiKxtcPhSF4skiQsJllghgN9DEbkQtktG5ROFuwU6jjv4CkeRleHNVONs6w/3y/ZJWPypHfGz6G55irjyZj72hTZSm+I0sgsTLR+rn0hT6r3ILjUjwdy5NKJibx5Y40aPudX/mCptCbXm+itYXHgJ2+KKqjfxOoUBEPvLpaWk79xqE=
    username: AgAVf72bIpU5441dMY1OSuweRuiw3aTEeVtXiIF9H99uGhG0rJMkTrGkVOcnhStDbKTn+ksHo9xsS+VmfaeiEVv1R211x9OTHMdb+sZj1ohk+WuoCGE5Ih4P5ycMt4o+pjyf7ROvrioCVeBtftvj60hDROhdzE6pj5C5dwr3eL/IupN1HdhHX8/OiFACXWVswKfiuKbSPfYVVpurLFnDkjlDC6zEXPw3tTh7XBNARBLy7M27EqRKhOIdwGfXPD2yOHYFGWH+1/sFjgnXzbDgjnUZIJ/JuCzXghWX27Jp8A1aQjj8w8X2cMYgZU+1ThOtdb+Qmt9T76Np4JoNr0dqmOgmbbDAkNTkKeikIcFy4Jxd0auatZvI4zniXEf7mvVjgdW3rLBlYK24TtaSGp9WfTwOYNlsr7FDFTozwIda5fyPV96QzpTyGjG6KbdpD0uEv9Eiz4dTo4sMEJP2EKJBT9b0SuAOzEsk6ASiGyB6NlQ8aLGvTt+GTaP4HDIxO5ISZoco0c59uYJjcA5ON0Z/vgYy9//bZw4lh107UVyHeeL2EDFt1QamKV4wJ/M9oz8OSO6SdEufrfESOZm8E2eytCz9DFGPJoifac+863mXeAWzAeQTScLIgnXZokjZcuvo6l4DFfEUdtoJkXewByuU+F82OECnH8LdYz1JOr9H8hR70J88xrar485f0GRAYWaAeJKx7LlcRg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev
      name: gitcred
      namespace: ci
