---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgBj2VMS/mxS2dZ86I4S4hbqECO/wo+mtWgBWu0wwIXEzpjx+EMziueQsufglLa1fkv5wF6Egcayx5V84Kkap6/vy3Ny/VD465mk3t1snRhb4FSTU5kkXq1NS7oKmV8oc4ASz9aCV3BsLixVASpVo0g8MgSFVAjOlbaWbVxArg0lO6UffJcrW/Zgjo/owE4xbGbtbkGK96kTG5NWMy8jk8Ktmn31BCDFMSuYJgrcxc2NB5HB1XyfKebHFOhce9qq03PR7JOvC/2Ur46Z+BqwxWSJh356mkSFZHkGY8FA/+ZGm1DliK1plSMl043IMGaOhiVcBy1jRNNPmDK1ahmpKnqf54YnjdfPbjXdObknEuVS3E2eZNOoz+Zg7bOqd5vSpCNQNQopNIzEKvtdmectGW1ghBU39h94J6fm0dasPbcVD+a//o7e3p2NYJpBVTuVHn2YId/kc3D3shd2xbCbNqk0tchqAB/umt4C8OuHl/0jEfy6MelBJjmoGr3L8XAsqYdDSMgbyV7XsyKXGy3GmR+pezRPf7WziH9qkKF9BMVnwcIOe99MILmkzSQL4l69yy5lmS0AlSMFWIZUynt7iWE0IUSmtIh9oqpzCf7HQBZjhWZTK9po781UjdfGFjDpiLetorikrZHGwrtTqL/66Waz4vteocCTZe8osqZtEmovv8F9B19aGTdhFdVu/quzVIph+NCO/AgGxis=
    username: AgBNUj64fYtnPYL2mizIaiSX1qpq6t+ZUcI0es5qssy1rDelroE/6b5Vl9oKgQcFv4i3AkWWFsM1hYgYVqbd3st413M8VDmm0BOT24ZeUBVlRu3qLYGQxHHbxcTMVcGG6ESEadgMygiwxmAT9dYq7ilqFU9PkfNAC1I74j/UdHCGe0cEP++jBupUT9doxY0dMcyCj2VFqztdXs9pok7bug3xTW+mbsIz19ysiLBHzWtlzOc7IACltd/BPEiNFD3UlcMr7H/qYpXgmqdgij5MCGNU6DX+dylM/2HIeEhVdg6+k61A5h8vDyOH5ELcGnI89PCpyccCNSk7gmFzD0YgUDFPwfzvXL1XX4CtNbSgRS1gMivpDZGY0eZStIRDhNP9KpoSifd4uZ9Hw16Dfj8X/bSwYLasO3+rSA/ZFTPQTQCHb08Y/cgjl8m0jbZJwzSlGozl6acP6gXraLrBjH72J1QO6Ulc4g8rTsJB4tXoX/X+qlcC3gcIIIV61E2audmQ8vDCizzDkgGYWMALfv8hzt2i2NGY4oUXEoBC/dMt4Y7Ls8K6BJl0+6lTuXE89BiQPUH+5uo86y5gur9WociFcE1EuLcYPeEoBfiizwvb+I1av1JF8wzHM4gRjfPAwazMTBxS40M7cAlA47EbUtVKQZnuXQD1PS7M18XQyY4H2/Jb6ozJjANProLStEO8iRAyzhD/e4M93g==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
