---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgADx4PHMgACdCdKS4Q29g+t7TPVXy2XePkfbckhvYmJezAdhe7lCa01RV0FJkxWTRuq5Rc0BdCgNtALlJHwjt9eIabtDb+Dz/7uRh+uSaXgFcCMPaeYryL5izpgySiGoQe5ido12C3leHwh588vY1GKA3zg6r26guod8FodIvrYxOLbTTCwBVA5OC4sWyfxyWtyjmGmCHSMvshu1LhxfjrUyUUr4OrnJscT12hcPLUvWmB2SOcYhfX9szvxDOolx9IcIbIhht3G+A7oLFq0SCcIsqqtXbD/eA0N3NaZZRobSuVys8qDW8sEj/wlOV/uqnduSs11qUUh/shB07+whmz42ExQe4/uIfkmpG0XRQ6BHXjlK0ZMU+IRe6guGSckzkRUQ2BVTMnjPLsjwUGZDMcXraTxoxT0WplaPkQ3AxJ6120vzUmQlrRYhnH1mCByYjoQp8mabhtufJQXSQ9vnn0CsOCWCec61MsIaP0X1yLJ15cE1+9g3JzURwARrTDfOGLfT9UXlppLM3+xyttbfKsTIIkTIfaVmPPgpjzHvZOY6T6kZoR65938wzYfJuM5xvnQfXdzmQ1kVS2TmuNujiE1DYXqPzRq1dY6Yon0PCvvu8Oe7jaR9nWWIzwMEQoRiFbepF5cQ0PJjRTkjOTq6kUq3uJbxJ1GNWYj4RQYQwZ/aj+48226Osl8oVk5jyIUTqp5qxE9wbFfP2U=
    username: AgAXOI/ydL0kOW11rruqkdogRA9VD8AT4ODRZpEgjYRaFjNyQ/PBwlgIqjhoesKDTx65tE4CVkhotTBGp7reHQES+v1U4WUQ0Oax10CoXerRF6u1MrI2Jp93n/ZyLCfd5+aCUlx18XcEscMcUkBYJ1OtR/gBWJM7zec819AFdT11U8jR5Fv1iEY9JX2VM1Dhb2/idhR5296RPKAk/Q+jPOhN/GLGllkV1ptfBp/9AGz2g6WITHUoV5lCX8vZnrhay2/nzNpJKzmJpsf9O5tsovgYRpqQ0apo1o6fKo0SlEFI4T4sgyg8j7bjo0g2zuah8g/VKbo5c6MSJ7wM187NnP9M218lqoMcdXyUCTkIRxzgqNKlViZ2bODdXP39BgfYL82yyoM6qyvbSuQcmgghp3QMUrWWy0VWv7Z4WOFzBNh9J6DiAlHthkDsuF8PXaqkTFdUZk62K4B2a6dC9fZ1taHlEJw4OitdkX+arCU0SmKrKu78s9lqaPXmXpawmcCBIP8G3H0qU0Ddeg2hli/4tp5hSDJDVC7dxEJwb9UNIJ773t8UTKgkPnnkxDGVaw3JBo9TP4n8c0IWbr8+P7EqqTo6WWYs2msUqBcHISu7PV2B7T42KREWaJuXihBroSXffbozZuipjNE3hSE6Fuoftp06k8Q3ikHZ5b3sMpLs4gIwGA7Y50pBvq9KZNFlXd+x5oDHQ6eo2g==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
