---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAb5rPnoPh76vIe9q6Mn7ByMvE4PAlbz3w4wwrKpMtnWbqaZVPRkFwIV7mZ854PnFlkULrRc0uLOsH/LfRzonUDrRTpqz+vuY62jOsaMdYwVrB/1d1r0/JLP3Lg/zkebtFyTpU8GAgQ/1BNVIt7STc8+6Mpn/AsgNrKFI63a0Hq/IxCfCXaIF93sNxUzpRwOegSovRskQXFiVBs3K4662LDgypspyt3cvBOB5J+aGlsIKnV1FEzJipMLZ4oz5eEeJVLE3yuJhbi1SN3bE9CPCvuaoQaWMoAPW+rnRCh5drZvcTxV/9J1Liv35tMyRLLR9BK9ib7vlBd0NCqJUdZgCy6sMJ/sxvi0VmJhggcmo/tjJ6/gt2N5BCyYXchYINdoeN2D5To0GydHnZSuTzhEqOlmy42Unl6V+YpVcc+szaGxnmKyTUWrC7B9FGCeFH9QeLLndGchsesrxK5WB2721GiKEXlfENWmPBFTI6BSq9G41f+V2Xa5ELAtvALWt1yIEaAR5ptMHhXSr6/pyEZyTO12q+UuSryjRxTGYEDnKmzo+GjcsmOvG+MDwNEM9q4MGy6xbAmhAO+FWqU6x7aeBbYxNuJkZbnMpKHqi4leQ8kEWss4ftDoV//Cf5xGSftwGYHBRPPFjom0ZXs/AVx0zEqXCuuSr4Fe2GZMuDgubJKcjyubOQeLgZObH7vKUTMj/z0xJCcIg8EzxM=
    username: AgBtz0PG+cCoUK3gEb2I7WJ4UcvOhfVLWh86FSYqywL/iO+Gl2IwSMo5MQsZk4ZqV+KobyjR7DGcHI0tmOJvnAodd6o7Wt06MhqS5uPMnf6aAEiDnAzQd5oh1OT2Uh+oJ61QvPTg7/BxYNt4wMWuGMur8u8ot5mWze0+OXptD+ZWLH7lvLA1q1GhhqBM8EIghXKJv31b4FWLYOF7wuSPsbv+NNjmDrERcXZpanw3DXeIYxL4RsaWmSTGiNCsdkjJOx+MrC/CFk3y6O8iN0tiuj+siivISax/vfP12DcllWFYRx3XInyeYYgJjgMtCUqLxJRO1bhb1FoBazQ00KhiTwNoz0+/K6b/tJF+Pqe+/EF6bcxBdoP3/0giomI04BgIvjI5ofSjH9IrhwttlMWgTTNyIIrW5Zl9w9SUnuBr3npGNdK4Lq4G3Me1qabhTf0xNm4DTY7tmabe/n06uEe+EdUHbh2XtpaQrTdCMBWXiG8+pq+po1ht3noE2y1XBJ6jCCOTo1lH/iQsCuljmDVzKUOv3reBiA1f9Ijei4mNCosSXz5x4WBHeQ5abiynnRWgk28uF1qSzvm56kSJMO0G6ZzG9ndCXLklchNcAT/IJi3JfqTZFzv5y7fC9eTaYYDpsdRWwCkLvzHB1C1V+WJCYopIzsHK9RA2iJja2gS8vjIxg8cWH1+1SE/Gs2F8dLHPjDk+UEFVhQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci
