---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgALmlZTGF11Ef0r7r6S1nIERWaqknguOSsIuiQdozGvdj2VoV5Na2Ga0L19sYjKAGBu5huIsAY2wquxUnyqYs1JGgLYaaMKEBYEX7OHtZd7TnGqkHIe32upXJPdq1aviWj+b37zdnTEOYSIVPPYHnOgh8UCzov1dAl3eibhnCahPi6ZXcXmxrg8d2UdBLNH487ARmoUj+mbnSpj1hl9fd2ZwEJdEsg5OiJ7UZAPM7uSr+B/amwk2Ixj2XK1vqULaa26B/cZUDdJc3gT91xfrEYY7r4rkYjb3bRX35/Lgw3n4zeTmvJEBAErdksYFt7eU9lh7iwvxqJzo2CZ7T4vM5pO517k2xr/KeZN7q0XKIZFxoYqZrVabHM0vA2NY7LJl0YadDpvHh6yT1ApMw7z1EknhSk2HIzD9Dlxo6SX2wb6SNhq4d7a0CV6DCCXuDt9OMQlAyXxaLGm9DA2sWr3ZJWYO2B6tuEXK2QFu2aQlCGLoPLd2yHoOLLZ3Lo/Kk7HUgJfIBv5ROK1ejsCyiALFoHjsdrGjp+NerixLS8DsdVAP3LjsAsn3aoZ4kxPozaIWhRk0XW7UC5g1BDF/wuYPZzrQ++jSFg+ez+10QXNWbneGID2ZgAzcMQyXatgXs7K43gAG/Ua40VSFcFmVSPv7nKfKfOlGIUaCDckcxkRU7CBYH1PjQrTOMYsDE3IYDryzJgWpGq2Bdh6zEy+XTqMHoRWXjUC9h4Uk3AIpFGadnPu1YBX9FpNGTQgtJ8RkutH3DCL4Gu/GLcsv1y/QSR18EiDEv4sqjl1tPs6yXKYSZrdIqAtKmoy5EC9SMNes8BxsWOLfmNY824FA/9E38Nib5qy3+o09Fs/+Rv7P+2+FhTKgJ2/Q751eFolREnDPyaA1VMuOPVTmR/Hi6h0ixayI6yasHfuQw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
