---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCkGi8yovwYZlqFUnZzbrghbOyp01JLG3WmPi5CwJt4pg8A0LTKrCn5knTXuczT2QuHLhQf8NxCdnwhNfdKacOBtXliJuwPOeXAsV/JlFdVZOSvjKZJMeMb5FbhQnG0/iL/EufmncvJyVV6FiNppka0xyo5wWw6seSk3EA+yRkI9KjgNR91LJabBtBxrDkq61VuFFmA3c8IRk/QwqIRzwAuEATDJPokiP5jY6NWxATxNjnTUwIJexoU6zgzVgEg7aqb1Ip5AD6OuF6C1wmNVrSiKtIlKSI15qXTaDuxH/L06Tk6UtT1l5YlNsDLeXR0W6GD0pnoB5soZiDCE+t9RHSmS4Qt1aKDIIwJf1yJ3L9e6bX7nKWm+CtzdDQwexuD+GN7Uk98oQdF0o7BD0DRxKsrAODzgbMuR0P/qNE2AGeIV+FxTmx6qJiW2aiApm1FQUTJ7tkdoyCPfH8pvONGgsBUV5iEckAzUSQAnE2EmRG8/0IwppxzIQSFmfb5elFEwkh5OMoHESmo49XJyHUMAW1CS9RDzUuGkFW7AYYawTTK+9jPPkBPz2kpUQvGffxBETlSop/YjIKyk+da80AkgbdBS5aW9zM17+Z6CCx417YXe86mPidzM0q9fBJh5CttUpNzd3g8bmma3bVntk/2ltldZ0XYSIcigG7/Bh49z1qPh6BRKPSX8zH19qsfHYMj5Rr+Q2S1NksUxtOn/tARZTMcJCbKLPwRbTxfHqrOvNiEVxZN7i1PpogbUsxoGElVMAfr/awOZc3tI+TwD+N0KxuqvwqZ9Fdj111dapmJbgHkpuChepOhiLIVzL/Cdi9isnVDXDlL4pLKXYss3GqA8d5U3ZvM4LlNojUv8WtZSsKq+EXX5IPZ16Sn5FAaQkjal0oOPKtFJ4iywc/cV2R8PAAuVM1AFAo23IJNiQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
