---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgA9JplHUVMNIHGz0QNc1DDchveyOZxN3Xz4gDh4DGWGZs2DgRZKLxIripSrmxG58uyScyg3kR0aj/EC1baAy2lqo0N0QHuqTfwiJfZUf8p0kj4zr9DJNSa6ORpQD6PnM0cskAXsT03hBumN02CXWlhjHbYAbXeL8BXXPJw245ihoKW41a0/gWN/HKY2uHP3d8YGFcAJdfE2Qpq/4V8ZFLunJRipUUa9tvYSWc5f/tYZu2cc8JkK5/70dGnP72484ENwUwv+H3kzoLWnvemoah5ymlo6yw9gG4LNsvxkiHH56uOYdZ6MIYymWTQ6TPF1x+/H6TUvXRMUuVUUrdFhqbpJfrueQDBZBkBLPY0cc7brf4cnubQxgCenOCfGbVx8kqRwGtbUoOuxNxb1bVpvqOPQuio0VbUx/0fwx675dIbj2b4I5L9CEXYJJd+JhG/pGQ3C5UaEPL1dpwSK7XTvCDcS/66d0juQQXrMwUcDclW8sti72MX/P/4LWjBdhwLp8d0eXMlXoVOksrdQrGeFJejVP5LVT+8AuIJCg1adXydNCSxayLPZ5TPjI9fFB4+m6aq3/XtMIoaupapiDwamcv7e1qDiy7s0/LoYntkphi79WucFYItlg1Va7nTEqhAitHMpnH29Ntv+Eru25MQPa3plB67oLOru73lTfKZ0wlTsMKZ959h2jrtwfgnYIr03RKk7luHtHaxPd0qZFpHXxRoJg9Bv1PycVcZJzvxEl5EAXohTtt7mIID3dz83ne4/k2G5y+l/8ZOLBzX16zFXr30eGe/27sC83k80B/E5zk9HcVumdSjEZOXpSI+CFiD9qCj/Tg4ddYDm7Uy2Gt6qsDwEoVWe4hg8WKbFlpQfJqb2fnGxetpZve317lRUIo96KFOggtxitHaW6RBbIaIo8nFkkg9ksdzYjjVSSA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
