---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCXER+b5CzWGo+egra8YbTqbAMl3Z1Hfhnz+24Dh/E2r+lqatNM+7UfIf1kgxxA9VahAh52QAKREWi8/vYUs/KGfgObq1xHo2CwP1EPm0syEJA2I4FNMod5x/Zcq9AZIClZ5ZX6KPNUz48MmvzCMkgxSszpmzHg0jU32r7r82o/cbIhfFS3/9GnM3Bwk4lgXJW16mGiwgv9zbVCumKfZiW3Lpdz9Up+nk5WeuJCZIdWq0RbbWKAmU1FysKaT518nC7Xi7Xsk1ilbW66RifpcvN6Ly6KmAiqif6zsMM6zvYPJVXJ5kESOTvKho9s19nYAb/o24UzMLDjc6ihuBlKQYhcqodB3xHG/4nZ9KOkYDRnjSn0464AactWrG+EeAZWzTc3X2yhHHG78YKUrZb47Z2HKjg+AsTbQrY62PThVINxxaLFvRPTbD53XEhhhABO57x6eXCNBLRzW1KLUxlnPR3Uh/jKzGPDdWhofy7IEILPrR373LowuimCgV8A9Pd05ofQjvMEjxLjNDm8Nu8PFm0YZrR0QFioJsWjqhEs6STBTGamo5zSJKN7lLgD45cuZL55fnoThzfbJDbricIgB8HGU9MQxoiqp1WOiBesspnxA4oFGDpKHXLJPDN62K8gNs2pWPt6jcqYMdGf1ggDCAQYQOYYoMy82W7m3QOeqiHon2plhHGgbvTud6Fp2ItrfNwpyztzVMSOwHjYCPa0N6adKn3PHyPfPT4lgVU2jKRqqa95oe0TFnmy805uipTSXfUCWFpQce1LBJhIMJfPa8XulN8H4bo1A9adXSRpbIwTzRZXbPPsZtU0T0C2sikE+q7koT41eSWKkx/F03/5P/knzZAEOa7ls+hnTeAJllF9vKSXgfNXVKOX5Y4rz4tbQYOamlUP/mqvgd7V+pXto0rQ6qw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
