---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAR0bkIgwDZPuc/NOX0t8bsHf4UygQ5nmB5j6id7FFveFJ+1b4p9G7rE38TEnjK8gYkPJtsrNbZZV27rK+5pfqD4Qhh/FpbksMaY5eTSw9fsj/aFZ+I2RF+8msMxslKryryo6nWULRvkwxubWqP7HzcKVOP8g/wZN/S/n9ZZwGlsVvSDVoKy5b2trPLUZHZo48FegDVoa0vRHrlSWdOzRy0CJ4qGhgOkxj8IBsXkRWiLMGd33s4ej2mui3m7vrcdVtuT/nRWW/M2D1itunF09YeujHdJR2drh04qxmrByEDWmsK3kt13kr5mSRzHktkiIiUxOfmrWXSWhI+FLE76kKFvQ7+RdnlPgIzKVmF97H/vVuAu/9CjaYpsg6MPFzWtsvCFfUErrdb4cMU6RJdzU1T0/w/e90ryxIDWo1Hf/eBk4aJlarT/OqGMDJZTOsjU6w2OAEb4Ot+tPMM1xiCAI+YXjU7saCANg6OLefmbYKcAwPWwSqXQKdsoYYdhRDx9/OUkxTVucVrqkZUEbVt9Ai6gFWv9uTOsy1Kfsz6YHoHOkWvdUphSlokVYuzzJZ3SeynveByGVjH6UsJ2kxu7IuF5bcWZolN9+LLp0rInwcbKwi7lgP4kXg7Ap3Ay1n67nwfwoULLIoj16E6zWthoVOy29KDnwEPLVa+l2cSpr93ndrbMhdw9rIeJfF2rCgp/9iA2FmjGyXGKryvGabnPTeafaqICa307SB+gNHjrJmXViqKd17EptOk3bxasgj9xl/khKnRicaf309dFERbH1J3CoaE63x76PbwhjbeFFbtvTrNx8svSSH6ss1M/1q+JkcQiOLGFhQBVtiPXu6YgKBtsy6poERYaIqsSP2SVtJSeC4CI4dilJI2wX92rf2F2o06+GKDnIDxHnEX4RQeIIUvXy9w31fAQOetvA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
