---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCCeOcmiLiUwA1iv/WtEOibaka0NLcbJKUbBs9zKFFK16k4UWPBHsRiQgJmtRmuBx72oTlFCGPKMc+ucA+xcU+20Vx9F8AMllnUpmdKht3irRA50MO+7orm7P4Jyiu+lvh3j4A0NZRLeGCKUpKAO2UFsaXlIRiFbxlXUfWuyaapMeBByIz4aUnsCp+ddKU1SBCzv0AIluEakTAvjYew9s2p/RH69MqabV4u1c3Igc+VBqqECg3KdFMxruQPOzcFzJENq4qS8z/3Gu06IGCx9QZ7ugpg9gdjEC+OBNjA8An5BlHT4Du8Nz+g8rDJeWE+6agTL6/laMBVcPaBpMSa4vVCgPt6Euel3fcuSRnKiunkxNkMEkGRV/nCLx6rAuTznfgNDmR2elz6UwVSGx5YJKv7DSmSrEtVPw5uu5BoZ8+qt1sFJv2v/paKHI8fTsJYnBx2GfSi5kEDy4xWa625px5rJzWsnk9XHsFovqyV7EL+4qWYjzzIBVWKHZ4e2py2DOZxekNUMreLSBnJznvwoGsYePrtKRBobO06xb1oHGkDD+q0/hSOQb6UwOd7S9nz6pzZ9IsBgHKMeaT8vyXZDhx4Gx2k96UN9Wy6T2+e725sxJ8KY7zxA8djjn1nuvnXbqhLbuBWxo3kRf5aWInnydxsGlNANlD+oruBlsTCygTkaD+psxwlajds1cnmUmGM8RIwfBuZTPXc9tYwXLdpTDjqE9EWZbfUKeqllbPoVONEioG15yNydAboAfr7+tN8SQyRdnhTDLFGChsoQwp+NcoUPiQH3TFKs65miZF9+7qvRUFHPFS0iZDMI9Rv/JMLsyBpyDAlmbgpkHQ2dhUCroHuGsZu8Si1CfWYUDONn2xoLOpjMuREwRA+wSc4cO1QXH8A3higEZNYDGx3Dc1AYNR6wurGAEKiyPXmDw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
