---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAnuFWVYo6lDNu7JVQkjY4HjVz1xouI0Ey8w5jLFQImRT/ifQcAZoBIJYsOUyOZqchvJ603xPZfUWgwgmWAXzLGMwg906QApihSPj8a+cVSwFX4wnXgWVuzU24FzayuIG74+1wL8rJrPJY/W9edpa4BPsnrDzVsKhrlZWJGh1x/WoQZmPorRq4cfPPUQnFYa/eiZpX3NYdhXbhOBAihK8BNj12u0leqjgwEvh/r/c8FI0gOeDQgV0n0mvOt2mY8IYLG1MzTaRWYR3aiZ2s6pGT5rhJ3rXQ7Cl1PFH/GsPKFYYkniNfmA9Fr4tThQWW5UfyxC/+rX+XYDSvRDhmymg9B1+JdnEF5c7ZLTmapugIdhMo9XAx8baZalDdozrlgoo/1sBpq5YahG9f6AuPaHJzsQhQ/UabULH3S857+3XWGAWQ/EkTlU9mBrYAJ/N0xzVwLUI8MrL5k6GirsguiAJCkdhIKmk9HONiKlvTSPOFWlQcmp3uD9oMPbNPAz2+L1YEKSE8NWQQ8HSPOY+MLN3jfuB7T92vtpKxH6GEHaCC95ecVfKT//7IG/pWf9a6m918cunUosE1/fFQaDwW/O2jE8rJPYkZXkVboC7eAVo0XjGJhZ3uBEbTUPe9k+C+blTfJxym/sWTNKM83ziNG+Q1jCPnY+n0CsVcod7Zn98vtG32TNApL1EoeVqMfKMtGWAoKx9/BvtSAZkn4IiFAr5AQ27oG+9pxlbThhRXxcY3OlNQo4izF7eWDwHujLAYqWU3UKLD1AdR9VgGdMs05y70yqUwlDleAIG+LW+Ce3ojHC0pWJvKB37sQq8x57FwyzZlgDRmeY7sxOTeozFi/O3mwLM4zS3TudP88arQVruEYWqaxYb9Gqi+tA4SVZ0+oDaU392hx0ewk6ZhhtDUWDqqCcNKjw+9dSW12LA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
