---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgALVUELqVuyLfyd7Gq4e4aB1moP4sULGINlIRg+oVGC/aS2MtKaBMDsblplsDOp/szfBP/N+GHdPZ/5EkMwEI56xZGEzIYmKRjLjCogSi+01ILceh7IGXhb8vSwnGKMARQAiWMQm6ezjAaDLJfDuM5J0GtAabSuGxFv2NI3BDXJNTYsqnU13PzYOuBD0tnuXG7uOsJyZS+d+s5nLQdS+0L8vgSc4UEtrk6+SdXnz58ZATZSC5ThB9rVRaKhkfy9KOlA0z2iwLFnomd8U/AFcRrNZexc7o/RkJQHRhcFnzrl13LL1XUGFCqHoZhb5KL6cNMC2ecSCCoty6PO52UjE7I/XTgroloyoijQrGYK+P4hCj7jpX96flHdeckt+rxbO9ZxunSjd7G0qQwuAvLRzOaLC4Vnrqafs5jJqdd798oabyy63p2AtyQ8iKHveB9Ax/A3EbqUt9jSEv8aeZNTSyKgGDf8Ts+RUYuRIZkVIRCfv/whAbhmLA8zgE3gUhyFpdMtlZ/WYkJXjpthXkep3+Bar5eFKgm4N+/WfnfJKWBIgVm/8cZ7DnFHEjoYgDj9guX5GOsZrxoj2p3ni74ZVE2I6Pa94hXLtCelR5owcG+oO25ndgdshrTPS/Ig4/hv2HDjBTbgzilmCrUWkK386Q0Qz81DfLJwPlfTau5jkZ2Bj6MKC4tzv/xi2RZRV6rdybNdgxy+rw4F3NuNJbOS3iXt9dxAMCKP3+iPxO6PIYdm+3E24R2scI8n2qpLgwLdB6mCtcmrdmPVEYCDt9+KHBmjbYFrjDPPKqqcGQapi8t5ldSLdSfoNjMHman+lYz9vy5vILGexym2qL0CaBNo5cGWImWOzRNOa76OvnjfpuuG63RPvXB8kl3tY24oDO5keQqUcPVJifCRWuo5ldVruVWm8pZ9bHtWnwmb2Q==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
