---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgBkZRjtLJ2sKs39pnLfjAOjFx752E+attP1HZpXVCaHYhK84PCK7BJesJhny5753a98Z2AFLiGNZT0y7tGWDSqM3A36/tvlAonD/UyXHz33kc3twKXmdYKp88oREne5XUFlv4w4XKJ3q2NCSDPhvohUxXVGtCZXFdWO3p3s+kQCjxUYTfXl1nPsd+XlLZttEA+G7ql1mQ6QTzL5ChNMCd1yUYk7Awny2HkuKIoJB3K0yGSKadu/nKS3JpjWreV8uiU/hoZx6k4HOH27wtNqpHJJL5bXoE+M5RSdPVJnUgv2vOA3twwpSCae4H+RV/uRuqrj+xTuEM4YQYajkY/DeLJ3KjJBlKpmY/ktlKXebbiVk10BQYNxaYmq3cbBhEjuio+5Ozkdk1EKhYdyIZ8S1v26BMsJxC828YPhpbe1UNE6uKGRt50jXlhuGg+tfjOvBYOAdBO9EkWWcei8alq5iJGghrH+Ff7c6qcyOxv8ojKOYYhWrSOMnFPw4t8VYAk7W+8az0oNMTwCf96zNWCrhsJncQZTncq6e7Hm0+I2U0cnxp59kGit5pffHZAivooH+6dfaTXQJ+0Y4qdZwqrRTAHU+86JkmcDoevO+l2frxfs+PyP3RO1ruoQO852a+IwydY9XstG4Q5V9eVoQOehCon6YzPY/5sSD738jhkEZQP5Y5FgyRnePrXo45MYGXc1hx9P2XrnSiHrnHEFDSGeC0sNNss39pgoCZl/YhoKiGPq6z9EvmHFHsySDw3DLF/DcVZtzXBXQVQCEZ5HF/MLgmMuz/o62Iq64EsdtMcF0VxsWhc3TdPrzXXv54FA/h8D8TL/6zgBdxQD7WCChhKhSgRfIKe3sADlavjBm0MbUvprHQ9oaUYLiMYBAzcTJrvF7H8Zmf5gJPGLN7UByxJGhZPocOc6Bw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
