---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAmYNCN7AEMd5YJaFUlcEFyLDx6pg7aQvdr2BZCioDQjZP06Z4pcaR8Zg43hJuZO2G6lUQ/rVXMKF13k3GmGLmLzcVzO2l3KC/TvY520pz/q9nh1OOcxI0w2NnCF459zli9mGKMEjTQizOgy6D6T8+Vwi6nnR+OhBjLnApU5/5Fjzh5jP8m+nwY9n/E/m67QU6bQJoHbzd0WaIs3y3nIkJZAGDXbSlm0I80pTOC/LGC5ANX1uI6NsiGN2n5j4fM0Vl5yP9tA97EHEyBekV02VXEiXDIOzdMLiYDpMYleIopem94hW00DKUqlQ5ZdiN9cdxw5e+hMeVEdhVvBwFpxBKPrbTCsEhzzE0TVFaY8OFBHMxwNYKwAjp5zrqUs54br6keXoCHWig09E2LAk7lZqDUnDPBw7AR8a5GOYzlvc4QwpGu5wWwTw1QkCVWPf1vbWpSHIFfGY21HuwNUX9Ic7CwRx54+Blqou464OiA2v9ejRyqQsisM2MmHzNnbsZ787EmqywI2lElKwRaRjC0Tw8Vs2ZrjeenyP8jQvYYwCp6NNjiw7EyE1xVrrhNeAp4IYJyjTbUjXWQYb8SgSXYmgxG1BrG96NJVEzMLg2vtI8tZazl1SOx3mDuYz9BuBqAe1SQUwWgjqYZArU3yJjZpWWJ3CqTKg0zQHNgucWkJQNXYWgC5lE5kqTwHD5/a6hv60td02tA5jaVtnH+uMv4rAByMyszdOrAKZHCJQOc1kWZnYEvKsX3BkEF/gn1xQ7wr7JcC4NtXrxGLL3rislUSSxFDdE3LDa6VQy+h6iK42LaeT/I9jsleywn0rT5AJZGAxbkruS10dTQtd5E0zPW6aqAF+JDQfZQB95hV+pjly9+TwHuzGskMPOVe80C8DDZU5cg1ZYFa7goLxlK9OrKQAo/TnnxMRnMqecKPw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
