---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgB7ObA642ub6yG/BbM7bWTqz/J8CQCiOtDSMV0erE27nt1T8fsugXCAjxr2WZPN80pg53e3tOFXAupkYGt4FrJiCuAHJh2GQ18r1BW6uAXnIKxTFoJVz8+qiUjn/c7xzzVOPITZNRSszgRgdwVp2edi7l+e8eqbGa9MGe8S69sgqIwB+wKy/JQyd5i8JgWsRdhtGNpYC6HbarN+h6aJ7Af1AANhbL8Y1j1cEpkB92456sA09YYDV2trHLzyYqkhowoI9IXbyWuHnr+vhEitJ7RuEW8QmRFJg0AkT3cPAt0h3b9vhtSm7phuiTsUX0MyGovtjbWlbt7Alp4oQvWM2A2MfiuUSZY838IAX6IiqJpfhzndQtnnoGZ22LBZQ7Rx1REs1RNTemFK0a9gTvNZf77GUJHfgC76pXc16l6spVvNS59i2y3OHZ1CLHcLIVC6Hr97NWKJ9vkZO74CirfdZi/W0NwU6kCKXdOmB4LcNn/TolHxT5m/krABV6Oponl1WeTE5TsJUgT7VhhaAYpzS4jbTc44jYJWK6lWbWaAJYzfvU685lLosG+jyQ9QEyQCATTbYvM0E5i+rXpv5ToQlzVFc43OvH/It4b0HWDmyAHi7AUL/jk3hkYzgLPHxdpgZXvW9JOktRvUbYBPLpn8yVp3sLgSmWPVvbAGuX3wTIvByYFgNzSXgwobFZddFqv5iDJSCP8Y7z49YWYrEh0WQmAbBZqPC82Wirf5IG3fMC037xCxCjDlK2u+9CEoCb0ZL/0KW7F95REn6IAzG2t5Z4uqWN4VozP+B/dYlAflPi90luW5Eo/rACmf57odA9X2hJoxsacsFiK5uvLhqeCuZAbDQvKB8lun/hlqISmRfWOwtGVTitLIR+biejCUN86L8Jn+FoyH62JiVLRAKAtrfGsWbuC1BqP1yxJGbg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
