---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgBd5pF7VDYz4mtEdBiNm2BTusI5J5ECCTOVrldREKl/8ItBRlSNxS2nJVDvle9IrCVlQs55vQEFsGmcqpeWpKwCxJSGabd5X1E5zdxMpZ3INJaIppRXxygc8tAP0BdhLo/TQyNcYePDj2fIYbM+Hm7wF/THV6/v75e4Uzw6ScMYzP+HSqLK9ibeLlaO8QlMUcPPE0Z0uFhTX+v0Pu1lXV/NV/DsFh9NDMvXjgd6geSqYK8653yjmrUahRu60scmgmFAG1elp66/PI3zKsdyOd8dSWoM/nqZaDJ2z9NGh5ZlVDuJGxFndyg8B6lkkWOSp4Dbm8xOAWwV7grGci9BI1dr3vq1OSQ4d6rBRL+Fiaqpr48iXlA6E15fLEJ2QFLWeklOWU9XgfR+6UPVNH6dlj4MLRuwytqDlC1da3v5F3Pn7lR07dN2fG9xkcKMCN7Fe19kB2A9lLKmxme9SwzSJuv63qNU397yDhmlWrn4Yfoa5+ru8lVB5eFRyVjyN8A/xdAveH1+axv/ICxgeRik/SsdqC4KdFf/0vY/Hktfa1Wm2mU+jfhTkF2yfQ3W/xLkL2IvZCc76IoX+FN4WjQFWYW1JKEIDgtr9OvJb1j3b57L0NG5RqtGCiZXTzremKTplB3Xcc1GTjarZBhlpDhJFlCWWSGqHRes4HuP0rYao+/m50wEuYtoQ3lgzP55hAXwdXACq6IV5KLZML7JvMiobDgui9mDkSy5VuaSIN+YdBDdzDj7rqdigfmh/UYEhZeCfmafXCB1ji4mngIS3cZ38lLvPGL4trAATaCG+ZHRMLivmheUyiGvKe6SzoRaRMorpTr4qjeVyvGCeJQw7Vs3BG/ujraIyWHtB3/Cc8KGggndadIrIIbxmKim4E+rWfUks3f9xvWfrPvb3FnThAgLk9sc5jSYyBpvFHEYzw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
