---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCo9ihF379cQ5bs2mNwaWFQVHKiTEgZ85Y16vm7yRt7TcXcn/gExwd46kJicYkRcN+Qc1sn4gqU/ojF/uDkYezPBJfwvBVYFKrKQX03DqjfAaXd2e8h4FjjHHXO1QULDSk20QF3O7RNm7XrurK9umeGW8whBUUiBoY2XAH0gyGqsn0rY+HhuBADWZaH17M8cELK+ACH72KlLdAraGv7ZCFScrX15BdFBqVC0VYlluIvrB3PgpT4sgSkFXrmZszwjKWNY59Nq7l0XUC90yCwzzGojD/gj/dBarUoJrMCthorRcqUPFPaZEWeF2hEFg0KhEf1u/RRTEfwyKgh7W2PPcWatxr3lLV26JNZbPgMMojQBP6sNOzj6NRaC3rHTUcL6t0iLQaeJGJV7s9NAZMgQj5ZnI+WHCJsTz5XVtLHVYaFvbhwg+fye+M53vI/8iCyqGFvTAJUoOk2tZRdwnNlhzIQWtjgrHhWzf/70ti/V0V2o6aN1dq1QLgfu/45mK/3F7rQS98nC5Sjwcxkz9zuOrgbFisDzbYtHr08lXg7meB2Ll9vapKGeL5CAlEza7VTI5LQa+YAwaCJusQVepGTiNC4Y48+pgqJBfyX+dwmmKpSxR1kW08ToXOvMECA0jtT/gNZNwklbFLE+Kg3/GU8NL1fLSnHT37jccUM8sdj4wcTm7ozbM+hbomofrkNMMFcIg7FujeEtxnCQEtTR2azgvD+pY2ms4zNdK7qYmbE0FIi3laICCcmk6CWLzJW5tMOqMsBBvpF7R33/+9QU/jHlCnJ69/EWoOOWRYAH+Di6kgAnGCMkaHQBcGbsqGLgkyIDtuRsXb+ayQB6AsxMbLfGIp9ju2EB0Eesh6t4PnZ9y+H8C7YxpIsI9Eh7QfuykIVZLSbYNHvf+2oTNSrA/8S2A/nTCw1osdbDlHU9Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
