---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCOn/4SKmnK1ytd3DoTWDgefrVmr83QR2siuyMdT+9JPxUATFIdPgsoAP9xvTvkB2U3y/p7xUZs8wWFhsf+kj1gL66NcJ0pswosretMRSsFTkx8dIfHPO3djfh0eMYm9lTpFxoQBlF61aw1QU7DOq7/WTmFgUC0SCqgz6bsA+FJdRI7aVr99lREdC6VbCCs7qq0keYGY86UbcCaFAMERSYppzo6PrNnIj6Q80sB0rDXp6Z7GwXdcAQ4wYNnnRzCZPk4wuvt3RgQofUTPo7CAWmom4NpAnj4zd+aBVv8tB5yBiVyNzVq+X/oKFTmyNGfkOzPZ/Ftbb1jq8vXErWxZCNWZEKmuXQlruqsThdscFjhwlVB24e09ihRS56Po15S9TiBGsbSnUgRolzXaISUk4uCoSrWlZyY5GXyURs1K5S71KVU3ACej5k4JF8BnbQdnoav6L1iS0rMZe7T3AbtpxTBkJebtxwONlNXj820g1RD94/wCm61fVnsgcpy0Ppe4h7X7TR12I/imO7cBuy09DVZIIwSnWiGF4VOFn/15Tsm0+zBLvzDw6m6SkNqsgZFdGMAbdisrx9AIhGB7Lb2CtL4uf3QnpZeMJaEVT2VmxW5PZNiJuQ+nEtf3tFK0HM1gNjMoBO4B7F9khLuk/cj5ld5xlONF8ZYssatkkPsDG4m//lWGeJjzsJeSB1XC2ZA4VOJJFRBFoc4Dj7AcU05lAQb+8AP24x2s9u85DMtMYCHIHZh9IuiwAC60fipmZ7QompWci0n4MfrlRpxX2sGF3Lf+MNKX/x3/10o9pnh1AZnLfjT9VD1UxhcrqTLouqCIAXsVlc8RuzsW0jOeqqTziZondmQFfWJFp7t/8N0Tsjm4rcTu0v+p4ycXmbCInIqOhGuIFBHMgv3VbsdcWR5ri2gBbtMxjkP/Ad10A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
