---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAPVcvNBG0O9R8bUvQV8o3WpzB+TXL/ka8mu5LalNXVbtYAa2yNMzP35Rq5sUDxkW/3+iV485L9PmnsDQlG5B5RxXatUyxQDSX41rZmmKytB8+2aLE9b4Hi9McOI1NoIsgR0E1BM97nw6z8ZjcZH4Q0GuYOalEJnOgye1pliviCybxAU2hbqoSyTh/DWmLG5KULDPCmCDjeoGq7YRHC+ilfU+c22uDEeOEewlwSEDi73VdkcZInnF1e4DJnPD0oElyng+SegotrwZA4bQ+o1HQ0GWOTQrL3c/Xk8Wr/8Z3yGrEYGfWLRoa4CO/5vzVzlUdl+FsUcYuL5VqyoL1ziu8qGz+YbC3EJDU3DPEkSOvBYLns6dyITMslXTIvBGhfqbplYC5shgG2lbrGBK/yi+rLOKyUrT2DND0lp9dCI4q0KRxJHpQnTDGS2kThjt2PIuP3U62O8sZ0M7rXBTylL83Y08kNUl7E7eBiZ32HUFjPq+eNTHzp3fo6tezbl5tbbrBa76U2LF/gUgM3ZNAN4VlPaeeZg06X3hYVzFGqaRJtoWjBonqatZHYEnl4mTTJPrg7WYqB7gv/+nopAPPawvMqC2vvIjQsQUYY9LFf/PQJ3F1HyBUdaz+DKfHXNOcKkyz5yY2dB5cNZ/WVFJp276/PltUJtgaiDOQ8qJVjeENX/Rs5N/k3zREGAsKMS7YUGi2WhjgUb+yxDw205L/8m0BgYIOeySYL1Jey1GxVlOhxRaI/Op7OPn27Mu3YOuumIh/WO4Hvy31TbtvRzt7014MJZQgsVS0tKN7Ybk0hglk8Uv1863QttuZa/X2yjlBbUOr95Az5uFZIolLb5irmwhO3OcsU2Dg9ks8MGuO3LK5IiGka0rQLq9nxXC4O7mT6gzWUXJbK55phl+6ISUf57hw6kc4/CnE6gm7KgA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
