---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgC+YBmRHx+uwFKIbcxb7SWdHVXyoiOMlR+RbPOjuRA/z+AyecWUJJ/AmHHq5MrinLJ2pIsF+78ir5wKZMgrVyq1DNsPmJfr7p406BtcETsWwLQNKM8HE9A2NGp6llZjvs7H3SgdRHwQkxADt/yntJBHRfz04xmN+xlBxQy9BMzgsmXzkD7GaJOu6qE0Ct3xEIBUOeweYkrHtTKdCMW6PUZ0mo5n33hWcd+o+dMeza1QZLxtH5uY+I86s16+sWcxFNy0Yn0p/T439I4Ht8xi5MijcZOD/fHm/Q38odVgHXZK+kD113XzomhuXAlBOFPK2UIbh/kFeRecAbKZQSThXZn3cBktNoW4pBbih3cVycJomSf/NMliFeuX8oP4KHlQNfEuxpaRbb3dJJ7l25nszEwJ2tFWXT91B6a04SL47JeTsJbAA+DKUZFXlIf2fMMDY34+HduyYGVUgdo/dbZS5ouCbHJDGD2AGw3POCR1VxL79XDnAB53e2zK2xFHJDqgvT9wZ5MUJYhD8PYd/DJChhDytuzsS4ZGj2fmKh5VRZI31El8fuRVY4jqCOEkWSsiJULtu3LR2rF0Sw4QDZ6VmlufV+hGVYRTwznK07+7cJUGPxPHfFUH02HTl5phfvjqRq7SjhPIove5jRzpkIctFB6ZM1bJeJYa3hMdRHfqT3iE2SNjAdiHID8AAVFIal3JScAFQ5peXBifpHs6vHGM3T27FURP7+Xa8FjTEeL27lJZwnvmXvxALYoIsutLiWGx4xDLYGUmExjzgGcTpI/MPtkCABFhoCTc+3fSHIgSWgKtR4Vk2iki4+dNasZ0lw9CTuBJ1MNHDlCtIufsvjBJmrxaLyz02xGtDEdqPJD1ohXQZrDGjcFw30CMqAkHA1iN/PlIlN3685RdnD/zQtmQIDSViCCpR8VTqKgcTg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson
