apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgAhI8pYbRNqSgLQhYhjWWWA7LF4PKz1fURmu0fSKzmsz2rHJeycc4FkN8PhqOgBrG5P1Ia85vFUsRx6TJlKo1+h8dsN8P2iG21pE5y7Z/Iyu9ctH2IK7wUlfbvsscZadndtFu5FKE1GT6tS/Jooz5iMbnj+tZaasdCeaKDGWWHcVj2FxTGP2ZX/bQrcawi0+WoZF189m64VRtdIUVMfXnVGVDCqfbZF5oZmqbppPkXt56w0MNoFCyiLwAGr3K5kgtudMu3rDX7cIU5J0hlAPi4sIty91ax3i12VwbTZnlgC0NJ7bX969Gn72ZFUmb0cNRZQPKDvOj398HkzmJ0qKreI04HfzxC5NRuxx1ir2XbTeE7Q9ToHPYxrb55RxzKrNKCgsSixTXjTnbmZRh50lwgKJBpriDGHMXmLRvBXSiGDjHchT6eAODGIUlDESpVfXIxg9SUT99e6zi2vD3NewsGBtxZ0pVZgg+0vTBts8VQLWnkaakQ3IYJMSsmLSZtm14cHJTp2ZOQsrWt8nqxVmok6lIcM36lpsxcTOaTm0+lvVPkyLde5GaudZ8GnoGiX1i+StzKloJ8fID22uC0VSWndWrI6wwFMPFQblt3vxMCaNGGL/F0k1T5qMiAlMPCAlOL5tW11zQ23KymGA0hIUiaxfbfPlwzCRjk1FHkxknzx2PH55rSrLy/pC4J6+8iERKV96a4g3SCrVsCKCcK0OQ+772VweF1OYNpFKeHbIocl+lqPXbonQabzV2sWMBoVe2qH8rENfyweN6ShAA4oQ4Ub6Wqzyc6uGDRCpu2zsP86Wtn0wXfMA5vR2RP8cQjRYyUI4PGkSI9VuCBCHnbAcXkhlu94iY5gaK3HaG2HFtKkRy+PboaD/1hshj5oXgY/0DgFYSfS5AhXO/lIM8cpdU4QqTCQSxJuNmwNSA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson