apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: enforce-container-port
spec:
  failurePolicy: Fail
  validations:
  - expression: "object.spec.template.spec.containers[0].ports[0].containerPort == 8080"
    message: "Containers must expose port 8080."
  matchConstraints:
    resourceRules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
