apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: enforce-resource-limits
spec:
  failurePolicy: Fail
  validations:
    - expression: | 
        (object.metadata.name == "devops-app-backend" || object.metadata.name == "devops-app-frontend") &&
        object.spec.template.spec.containers.all(container,
        (container.name == "devops-app-backend-container" || container.name == "devops-app-frontend-container") &&
        has(container.resources.limits.memory) &&
        has(container.resources.limits.cpu))
      message: "Containers must specify memory and CPU resource limits."
  matchConstraints:
    resourceRules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
