apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: enforce-resource-limits
spec:
  failurePolicy: Fail
  validations:
    - expression: | 
        object.spec.template.spec.containers.all(container,
        container.resources == null &&
        container.resources != null)
      message: "Containers must specify memory and CPU resource limits."
  matchConstraints:
    resourceRules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
