apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: development
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-store # name of the SecretStore (or kind specified)
    kind: SecretStore
  target:
    name: regcred # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
  data:
  - secretKey: mysecret
    remoteRef:
      key: regcred
      property: ".dockerconfigjson" # point to the key of the remote secret. If you leave it empty it will json encode all key/value pairs.