apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    frontend-push:
      port: "12000"
      endpoint: /frontend-push
      method: POST
    backend-push:
      port: "12000"
      endpoint: /backend-push
      method: POST
      secure: false
      events:
        - push
