apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource
  labels:
    app.kubernetes.io/name: webhook-eventsource
    app.kubernetes.io/version: "1.0.0"
spec:
  ports:
  - port: 12000
    targetPort: 12000
  selector:
    eventsource-name: webhook