apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: frontend-webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dependency-one
      eventSourceName: webhook
      eventName: frontend-push
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: frontend-app-ci-pipeline-
              spec:
                workflowTemplateRef:
                  name: frontend-app-ci-pipeline-template
                arguments:
                  parameters:
                    - name: container_tag
                    - name: app-repository
          parameters:
            - src:
                dependencyName: dependency-one
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: dependency-one
                dataKey: body.repository.name
              dest: spec.arguments.parameters.1.value
