apiVersion: v1
kind: Service
metadata:
  name: devops-app-frontend
  labels:
    app.kubernetes.io/name: devops-app-frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app: devops-app-frontend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80