apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-frontend2
  namespace: devops-app
  labels:
    env: dev
    app.kubernetes.io/name: devops-app-frontend
spec:
  selector:
    matchLabels:
      app: devops-app-frontend
  template:
    metadata:
      labels:
        app: devops-app-frontend
    spec:
      containers:
      - name: devops-app-frontend-container
        image: pnxedudevops/apps:frontend-latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred