apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
 - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
   path: argocd-cmd-params-cm-patch.yaml
 - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
   path: argocd-cm-patch.yaml



   