apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgA0camTm3T9nRd3OhRMYtyPEYIdtf1jVNmq5adzxS6FnpBYMJkmv+TvMxSPSCtRuADTkaUXxiWetR/tPDircbraaC/z1gjp0ZwtTOXWEQ1mLEOHoM3elorYvvNmgK67EZEx1BnUnLbeer7rFci0iBvm75P5ubZAFaJedXDpnGkkPNqLgdkHbqjNdAloyAeY+Cg3u5D9lsgYmRHTvzQRhSVUawnGBCoaAv7tbtxdDE4EtiqOaeadgX6iiCNgqVZGYwosFlr4r7azxzDunifAvJI51OulSDTTSAV6pOlGLgISRES5V5Hh43Gj1IrEpnzR+rm3Q6oH055Ncv7FLa7cvectQojnhkRkb+2zZCT8n3pb5fhurBNhnbZqEfdW1EAQh9+AZu39l9pwWfp/8MoQ8h0qmFsjeNZKLd0YyEEzi0j0Hr5k094+J2x8MySg/FCOEjZg5fqgmfbMUEKKWWg5UfgxPTcQu8y39pu0kBZllOTUMHDNcSEtrlYucqlRK0vsa5aM3RsECX5ODexdSsv/qQhMd//qcizdKQ88q019p5Tclb7/b1feyYuj+60JVbkpbomaYAtfGfmyEevXkuZzjnmZdtxpOx9rI6odfazA3WGXrM1u3Khla73ogLA/I3HPp+JeuYyqxsi2wdE5/OZu3X+ATTLBrefS+IX2ejfhbrBOCG07+p2CwH0e0PpDbWFmNRe1jgxsYHj1jaE=
    username: AgAQBoAiZWdtmfLvseXQTIe8ydj6EJ3yMntc627RWH7bbES2sKeFLlWPEb7VWiCZOtqpYvXMdkg3jU7DA4YxrJnySVgfU/k6tb1iQrhkpcje5Yf433o9NB+ITkmaBBECLCXtD7N9Z2+OMcQBZswdb5ZltNxu6AvhxyYlOVTlNwxLOV2uqGfAden1OMbCqrahSXydZ65wjckYPhjXzT9RqKZCMiSKA0bYq8N95hd7zPc7GkKHoR/hvorjzqpXOpyKyxylrigs3zz0XrqEML9i2iwDcxh+CLXqQMXfaa8FvGM5JqZKZK0BF78W4MGGuwRD2xVyhu6R9+sJhcVr6O/We23lxD6lDY7TNcytTgLMlOrncLIAQfMEf7TC7ds9KyqCPVX7+AWLKgG626dm3ggBjbRM3v/hYr+WrCpZBpkNBNT78XPhVj+fVEIxu4KxxUD2inADIRjF20Oi9xo1hyk9ZrEgX++2+LfNNK7JjylRtzrz7ixCfhDhzhKTZNq0rend5Ugf/+DQqqf4iYLXG9OIKKEdHkqV+Y2BBeNV4JSAbuVX9CVfM+4TKIjCIzat2dHXQzWIx3kofOW4SIxWrCv6ncTr5+lKg8Q1eRaJKsqp2d/YNke4l8EB7EaY/sK02d5SmUuFFjPkAypTSsjAhml2CKWsGvrqb/LiCrM4TK+KXmrNyJfW8k/0ul1RAClu1bvJVaP2gMMF8g==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea

