---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgAToeB8MW+UA6PUO54L4QPlbaz9CaCvYqnb3xG4IBel/wdbwvvUfCfvLvtD+sbuP1AEI2I0uRO82A2GbUHxJu2bAHcJWeM62CWKosQe3n/nxFK+TjpaEWxbJE3+2VCTv4KouTfKh68z2sF/mP2uhBXzuhu04E5r/OZkFjqukU7CQwKC3pIU93GyCv+uuUgFEu75mFqBNm8v6WVfipjvjjNsZOrxzZSynP9vHUCgot+l5WUMeekMgBULCE9roo+ZvuKuHxEXrnhcV7uwJVd2+EIUY3w9XpuqD5285lW3/kJf09UQHHAt9BBdu+gMItD2fDySzKRH2D9Xt66SPZDefgZmbbyBCkqGj9EBVWDqNZECVdcG+GFyUQrCrpjYxlyykoolvWGqM7XCggVPhBOmE1Wfq4i0tmXzq3vBQMW+VEyv0pHsf1HxH6aO/x9RrmNXPmNSDFJcASPmbhruvy9JYG+GSKxicWTYlF/5i+gElej9sVtGMZNzFK0ghgi0tRvgVfMA88Zwjp6g+xFo99Dir87BMY9Tiu2VtT/UNCM+HHQVZeXCKcBy/ckSEY2ltFhDMZjWv0FReRBvozHwF97UMwLtWlxm5uQEXVH8Pesqu7z4kV5DTFWHefcjkk8qrtWF52xHWSUlMFQgkZ/PIICHnq7Eazsbrf+NDEGpB3Vzn713mEC3n56IkN8uQXWG8v49ek45eTEQnnk+Gms=
    username: AgAwEf4LERTXQm9xvxqFOFmQYeqUGYmKFBJlZSIfgHpPrDy4MdDg8wWz331PhLelfZVNku7DC0LneCQyScoBIHNa73C6rDsLT1XutP+2cpk6vjWpWnTUdpbdry020s7HoRUzoVwPbunPvNzsydWAHe1YQcu5XLKYlzz2hV9BDsnq+A4ezmRWD9S/us+EN3HLR4+VHYpW+r0/pfKEazzhDcf6R6tB15xjLfEpjSwaAy/8vfuFPkBOMxZoniOtUx5MWJLRSMJS52SFYD6X+rZ4BlgHtKCRwi0irMu+hwrTXDyc9jn9hhDAsTaS7nSWexO7B95spvxCf5wyUPKylCItw2gXBJ+dT2IspG5+MP6FF91WH6fGSaChYMheMn+MNEE4oiuZtUKSOjL+xTorvwChv8lF9PrVaZuZEjyPYJ9+DFKkiLKUPApVn6WNTE+XW3HgNarh7IZKndUM8Ft8vG/gpw4pKYRXJT7bo7jSnzA/tUr7HxwoB/OUuoKzPGXIpsYP8rlF1+GtR7wQxGGXPf96Y8GRq46XNm4M4WXVIJ3ghSUltbKdbZ6RvgkW4+V2cGqUBJ0fNLc5wYjjZwvfXbRkKTF+/PkLdBYaEq4Rxbob46/HBnK14R/ErNroNVZelqPgpGjIRIlMTye0U9Mzikr4PdguMtJzGWkk27SV1U34dTnZ0XXV7aW9A62MxVizgJXqE6monMzcNg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: gitcred
      namespace: gitea
