---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgACRraeYwxOkhBjAPs0SQ32a+Rmrc0yaLHrL+5nFfimV6vUsiZnIyZNn+653AjCZCAxe2xcp1TCZNTibtQmR0spPkvV2UCgv4obun323LwSm/CQIhlJu4IHGMvbW7HEwhGxspAt3pynLvD35YQbGLRQ6UP+nMZjZO4qzAgaFlqXc+d1f0uUbm1Bj13/8xXJCLFIAMMJ7gKlTudwmv5nTTNkrVH+o8zT22bjcMuQeDTWxxTqmMrJ07UFtnHjUMcKgtLTQm9L+B6JX6j/owLO+4fWe++6eTGY7Eke5bl1CGR3cZlzG9NaMPU+dzMmaCDkReTVYJRF9PuSOGgvpjoVMDn4DKykxKoceJbQVKCGqdnQFv4Z0hXjbVSyb21s1yWuOBuvhbvo5Cs/K5K9TYo0bw+WLbrVQkl0wcN/gj8htg1LLTG47sFQi3hME7JGu/g665vvHn40TKrW1Qy0FM8feMe4ZRnI8S/WIPo1+PfYOapgX7oBRhoq314FxBI01K1K4mN+kvtQCz6eDQPCVguDKg2egrtjimaNTc7XCJHohxsxnUI8Zhl/FPWgc53kEQ3wQvSUvri9XNrhE730owCqGYhc96j5dI2BozKFBrH7JsNz9fvxnz0Ojh5Vwnp5XwW4V4AG4ol0BQ7AA1R+lLjqKhULjuKoCK10za3IUHX9VCXmZ7c3VEHhIZ3BC66Z/EboincguFpzgwg=
    username: AgAmnk+ENm5KWgwiWDc5YZOw8D5KcQsWWo+sWMjboaPFqlP79E+6IIvHUJkPg6hAYFbbIlfnN7twtrYyQVAHDaET/45B1kjTQna6KWe7QaLDUM2Jv/1yGwmZcf+iKTZ3SgYzmVfrGmZkg0jgjbtJc9Am/Br6jy98XZ1dbPpVApDdVdhdu1gFVznuoFL+H1HCKaTZMo+Td0ws4KumFYiEb5K9WtSCMQK7vmce4ydVrkSTdZXH2ZqJoiCExm4kjWbtoaOe7LxUuelDK4U89cmmyhjaqW79w3h+5n7qj5bdld5gFollEKSHTI/VGGe5TWlEDi6BFEzNpJJSxe/xW/I7SsTw4dbx+eXdseV6KnbRjRZdkRulwEThn4sxbiSDUX0/Fdpb3Doax8Bo/raGdEDRx70f4FaDPsiZ6S0jrJWLl8FTP08DOwdG3SXCUhqE2DM8bSig5vinqZDSDK0Eit8YGxVyEg9eEMmorLXbjjND5wW+TQd/56EptUifQF9mTLl0H4tUuRbTZRQ1GapsUWJz9rVb1/axuxDwmE+uanm8MMn/7tRUbZpwXEXp0EpHm88bNkg5gbTnrZl5Y94/KfUH3kqOUpNo7kZQbYRtGCbZuomjO8jjvHx5+3Imceni3KooghLrF2WNqoG5A3ivwX2VRQGpp7JG9rl6WhT+pDpXQpbKJlWw2LNI237FZTnRlTRwA32bbTROyQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea
