---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgAgcEBNDr9VDP+iHY1X0vTuogeJZYr31/ViNq57H+9osmi50qPc15s3HtC+vwwG7QyzhRScRuZ1YHoLXyf58pwumET/VP7B352Wi+8+xkqOMmfCDgLgol55EpuYqmzpaU5COrISxm/yO3ailahsG0KXJbi/G2HEBOQOwc2k87K9z5UEoYeq5W/XUr9TEIUNXDXnB/46EVePjutDmo+jvWv3pQVPduetsI2+dV0x5ZPZ1n9BvWyLrdT4kWOqKw/i/r63kPSl6Pu8n0uDMhrdyR52eXBakG7W22MwNh4MG/vp8G7f7CgkSC9fBRBqYowpfYYz61+7QiTKX1h8yBoW6x3i7pmr6jkAtTk14puaaaRj+frDJll6alQpJmZ8kVH9s7LhyMFBNNaBnya0FTj1/PsdE/kj6NswsZesxwaV+foh/XOp5k3295RzR52a21Q0f3i3GpPVSV8tD/bV/C/+L5s4BhJvnufF6oKOHYEKRZl2SBqNh8EHIlLWQMgnev/fq5h45gzzOsqH1ubFCICj4rX2bv9RUIWW0szWlYq/cUuxecjXHwGt5ltGn1FXx34PinBXKqI0CsCSXcOQi3q9aq8PG/EDQ/ot/jaJjwa3b8VU3N7t61J28APpWnzXrZv9clIKRR93JJkEc+XJ4V5vVq6gnml8g1mv3bZgHob3wKKVRQ/nEvnonEW0q2FFYTVQ2wCzrjwXAJd7j1o=
    username: AgAoXDMZNANmqRVqI4h72ORRNOQ2uccc4H5lsgQEFOqSCoze9EuISSRaawcJj5ap7/6IReKspYHdajryi2MUXNOtvneYRXMOTQIznTMcYgKdkQIRPGjbBttOrp4ziIy5aa0ZzfWT13kjX52q9Gv8QbGUoI6z6XXq+cEUHDq2Nf8gRMNSw/T9Unp0stX5l0Mm2NbjgBL192aIvps77M7cZ3ozYFHr7MY7yeFUDRhDZH+MuYsSghPu4LIEXX7H+HhblKS4G5v4sBwh5apHGnAuhJsqSc+IXpryHTPnzHXi+wqVVw6Atx9IJjRDduZbKabOwhaZoJ3h5cxcIzNtMYhzYDwWsG6P5zwPgKTBVJfgI8/LHLPUqmQEGHqrPyvCAiqUzV2hl8CZvHhvkeMQhwnx6RuVs/KeKuUXfy///hrffSUdxdZd/38n+m33kgpO5rvvmfZi8QlPSJcD5BBWT/wG9uK8zBpZ2P46ErCOi46V1tpXCi5aVbqQ+5QhRf1Ll0sGqohM4xGYwWmkj2zJ69CeM4w2Zl/wey2rpWUUjC3gtMQkOQkRu8X+Tp6XGFjIPkXqnHsXmFQYYJV7ryjuAsY5WX+v9EkZFUz41qju4Ffnq5uox1ZjuJ6AZNXRRXCz7BKVZbjrPvci9PikV6IUK9vtj11Qa64WzcICXO2u5+ge+sWt2IF5OcHQpdd9vY17LmoHtybygmYwHg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: gitcred
      namespace: gitea
