---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgCzTK8WO3VWyrBZWqfAzHbduUa8Xjt1hd+rbDvgTuHzh/G5YuleSaHE0o2H6n/M5Udz/xJ2hn4bBFmz0IjFTYk/cKZSJkfNc8cNJxLlamaxQMZ9aPalz48fcmBucPAySBLLsx09IPzWs6IY2I5wTeHc4FmADKhz82M11pgMP2E+mEL5Q8QSDkUsAFPmhYWIbhQZfnYPg/2iDcTh3uM6gRMh0776x4FP3O9fly2f/hB+4ijSSdhXNR+QIsbCp3TYKihVmWRYov3rEJJ79K4GTslvGjelUqoXAm6FXXxl6S/D/C7wt59cadcYj8IPgDWeDphJ1MV6xUnUd2lQRJQN+MD1BUHHRwECYcaxDaGKmx6ofX2HU5IDRcixDwXxYvlyv9ThYVSXpvQwYS64955c2N5zJg8MeHZFa8NkACDg9E6MsFwzDP4MTS6ZhCiWBcyyZ8WtOyMJ4P9hbz7twzrGpO9bXj3L4RFV9pQ/X8IFXSMrXC7kp3GuYgkZGktyB67oCYbCop03TQkmMzVjwkh/txrD/G/Pu0OYsH6YMPCRynC1Czywg+EIIXqxEZL/BGaKKUsjXy77Pc532ps2iQRU7H69pr+kCcuwP8Ft7Slc5BkawdsX9epH9hB5lw63Shfu4FlDWEMt/durORGsE5YXiC5Q7ZRUSBkVelfu4GAd8gnxI4Qvr/ss4Gxb38BNhkoBefMzgYb7soeATWs=
    username: AgCpgTA62oG7BXtwa1leBy7tryvnj/hUGYpv+ruf7m9LNTiIBj2C1QxQjob7AeIIpqSPEr0cd6TEh7s/eXngtCUJEC23KAOT1i2QkLdGiuzfa6Iz1JaqYfN4cxUM/VuBzSzhnwkCMQZEmWznjnSQ0BxfAel6IulpA92Hlwu1EyuRiGE7fgvKUw+4m8enVB6IXcqjaCg866F9d3Zaj+XIoanb3KAI3wpYUrFFrmYkNRsia1qoEKB2s0csnSXw7th21m7zrnECneBRir7r0TM5InzmZVlL+fBpfWN+MMWC4CBA6HVPOwtzTEhafE9m0tWCPICVQn3SEPF6Uhcj1dX8TY7MVcsvTPb9NCofp6wF9ibo/4N1oOB3CwL3c8Rxiu68iBrq2Em1vIV3WgqcrUknQocJrpPqWmJrXlocj17Sg31kVqx+3DSj6y467/OavKmdcbPDeeaQs8TSyJw7xK7brpsNmt522R5O3IxvXhaOfL4c9zyjdHo1TJL4AZLYjc2VeMtT5qT4iTDBpu7LhrJD3H+crF3WaRNCqm28fXUcb/TsNh9/KIzrzxIc6BiAobAcqncIHmAf1SaVyikWFmnUZ2pxau8r/doaepBq4eNnuUrUnp/oJ67UNc1U8mMTcliiMmCML6CaQ4WnoCKsoMx3OY7E9OttRgkOUxy1IkjiCGyvP1chav+3H+LSrdwjoSqsZZvparHTSw==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea
