---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgBVnmA+LHf+aoPK1g0aHi4dqjDOax/lPi462rWSv0r09lMcA/uvedo24zE7F19TO/8y9GYNrcsK9ost3LKe61W2nf93Y1/LTQXFdv38iOqpFyYk5C+xHkS2G22flyJgxav/B14borp6onH42qBxhaGnQ9UJ4Tjdz+EDR1g77Hk5Ql7UmaBu7+NUC9q6VSpppeEh60YgeSbV8XiimB/fzHuwOrTlx0aJVYMQhBQWb9QiqUJ+MkCXFCfVVjBsaB5+jS27RZfmzvH8y4GTM4u87DdoC3yaWJkZ5GgwKDG7VT2pnNuoxITukJTIugU4qslKHZMjwM5i3NFJLr6iYmfzE4zhgWzVUC4CJ1+GZwxikRrI72oA1WhMBha2EqJ++uHvg60fgrcfP3KVpeVJ8INXrBI0bP7U9hY8zK/48pQqeBelbBDKT61oWryayeXGD+dhrzS/++OW51dzznH2fjvGlzD0feJ0yP9FOY/jQ3uNxe6SFpJ3sZsOVpBkhg/rxWa8wS14WQyr67Ru5cJzQak6QxzbFTbF9Dozfx5dYe/fLljuO6J7m6OEG40KeIoSpOGY8Bb0AxxSAcsQNj/XyPFhUIwyGveT3CiBPGZnZAY4sU6uEteTx8LVFKkXLUj5jPLR0PtikXQZCRxko3INnVcI8sXohmG/jbBm2gv4p50sR8b1Ms7TYUc8S6TTUeeuiBRZjc3CtYoHwc4lMQo=
    username: AgA/HynUyB4Sl5qJcLPkbqsY3z9VWO8SOaEbhwc8LxdF8vU7GwieL+RkPl82lGwKt1P708OpVo622Z5ZZiBZOQf1aFdKwTyRflBP8xSq2FRwct/6BXw+Rc5eFCji8UG7ws3i0lfFi32Chb2rsEN9CjVGO5/hd4TPcNbLC1q3QDM8kAKkRRO2RFrqs1p6CtWiKt7Db9htAbyCTwHKtfUPusWTt1sF+yuPsYYszU/Sy3yG6aLrBtJnd4nbzuMCHg8rV1cGYLHJoRXO9pp9+3p2uqvxxgRD4e6gD40DPY5uRBvYw3l8IcAH8tNdjV0fz4z0l6MGpb8dt3riy9Ni3iQAHeuEY7jCUyx+59Lj5LsvLoqH0H6fQ5L+nu4EQXnDLOwWS5NQQ1qUHUsqUHBywlw2FiRB/qxxP7kR3qwkQ7ag9gfhEm2MeJIzlR87i2PC+AFWkpTk8nDmg/hirOGV5QOhgxsAC3Tu9yZ7nEGseeEcbrkcycL0QP5iqeAkLMNy3InYp9e3d1I+gSVIixH7l+6Ege22tMX7iRSnFQXjWO6svueKko3lWHOtFvYw1YjzxvCHUlFgZQccHgTPOAdNRZisyIW/q6x9XFpTQ6mYJYRK/UMlHNCwG5Z5Go3Lo0toFc3Vdjt2c4TJQejL7f07+KkoIy6tZNygkVxivLEPrygHNnd76FHW10jRyQoAERAhj1hO+i0Y6khThw==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea
