---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgBA9S+eT20zvzdGsWUi7aIxFDb2DR3kzXA2p5SJA1gyy1MA21Ag3RJhgXN32su+3NXgxDnF0HTBKFcln7Wftw7akhW74464LdOYHmyIu4RU3QXYQKQbj1pEDCHefkeKwxaB6sHySy/NdoxKKDs3sE1wg9Dwf49x2Kqi+Brc4o7gwzpnjihTRcJV4dy1zIOjNh3Mrtq3BU/l2LMhqtZ8qfG1I6/mbg1QsT+jPDYP/lwgNr3yY5nMhLNV8kKzmMLLcdR/2NdzI05CR3McMFHwVb1eu9xTlbND+SfsnszKh1ok5q1UyT4ZL36/c49woQrNqEdy3bD/A/wqlscrTdsk6jsolQBsJM9yYZ3LU0eupCA2tgbWXi3HgDWnRCaXVHEE9LI+uD6y80ORREc7azXwRsr0cUzhVYSci215S8KCMejX/qa8JMOXyLmUbHjsq7Gy5Ha4N/QGBS1jo0qRIHSZDy1KxXprQnM7fl0cSLHv8i46+ichsOwKnpYsHhEgg0mA2+fPv8inzWet2bUkHE3xLRZicZLoTI7WY0jDFFfJTW+/KrA0v40w+Yd5u8xQvY7jp40Ofg5iWnbhUC546UQwXgBSEgw6hfFOJalcI1I1AFJou38KLm80c6rJnozvJKRNNnZFzgqhFuDIGHqXSzQUx62m8NP6m0fvn1+6YemA6Sswpmhh3JUAu6m924VYH2Y1mvtU9EC0FHYbS9E=
    username: AgBzOw3LwJ0u/sjkt+6tE7uEG+96sHBDt83UMeMj/pgR28bByvj+eX4h2RF2DBeoBWL6TzbXlYhVr44jLPL9YFtgKhkqTD2AC2RjSJHtrct5yvilNAMBS/pal8Ok7uiPLSRnnOPWtRfddDeEHOYnS+W9pfRa4OB9ycyP6GbTNUEQ/NwjyGFG+d3BdD6OJQQ19LBRls0ez+tFVUqXc5EUhLX74RqcnAezQTBYPM5gVbhn6ZpJW2ZmPv1zBdqHBKx8b5BtDDZLycF3l6iNbjVS9CFm6IU9/jqf27UKefIHHtEuDsPCwLarkwamiHk2764PdnmQ4b+l1eErCEwtjPW2KIsd5RzZYSPEg+BvI9Jnfxxuvf+w2N7EbfZW45OIKhnKEKUhBdGA0SK3S23QvDeNV8BP2jHcGJ/h2QUUBjOc+Jng0D58IcMdtswEZirQefskHUd6Da8EK6Oe5PedYJ5/85sV2nulcKWWKqaAuTNq5mOfmd/PS9x49ejR2467EbgASFP0xSQpGU+384c/eqfSqGuHxwDIYHi825cvMGWQ8wjTIYCvMXmhu0P8vhTM5xQr5O3SO+F3NjbG1Zag5cWylwA78J1ax2ir7vE8SePt4jdMu1kzs+Tyz8FhrNKeZPFetHHTWZ2E82D7ocb+98oK7EtSwEfEs2Vf5dY6f9WqZ/rRnrRuA0vaW3/MIKEQcQkWCCKtbn2YtA==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea
