---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgCmCdVMtZlvnb+k0UentQZCe5xehDViuNJLg0ZD5nTmk61uMrtfsL4ThwuTLsqrTGInpcqyzpsuvbIaSenBiDW5jn89oUM59rIh22C1Btp7O7VbjagNW++kV0zx8FbGOgmZMI0YY5icUfQEWdrCPsb8ZzftF9QZ4zGAnycbC5Jn62om1Ib37xr7D6Tnyv8gpJjx83yOcslo6ZgDkS/iw5AJ3EfrdRjnMB9eIuzFpISX7ond3xIKZ2fll+Y42pwvNnUO/lJK6V11/DKlshZd7JLBM2maShmFhUC4bCwj1HeYwPB0un/QG5GoEm4h5iLcioIzocAFN1qwTJiRSNnIf7hQUs8dLFYui8cXMFtE1gQY+QRmupuwKR5AwO8sRBPkmaf9/lScqaXcegDODHmEZGB1xvP1Ue7LsMRx3E17BdauRANyImC291TwBLVbxcqSfqIPo1t85GTkRJwW/xHiFhAwh6bnOFkbnnZQCiyW4Z+VAibPjH74B/78L1qI436eeEbcwoVUxt9MojyD36top8EpurEIpM1IMUEyBwfy513t3BlNvkfYkRovm7ooTgppvSO4BMl5H4WVFKbzpmZ6bDN1KeUPtKm8axJgmo9cqgTboK8m9DsS9AqHIjbXpiXm/bbXHpPecZKZ65rx3Y6o7YxdqZXmtPkGJ+mGAv/GB+TllETfJJhunfSpYHuUzp2yb+jcSqvc63tr2DM=
    username: AgAp/SodS8rBeAtHRsm0CoUX7lyVUdBJCAaZ7os1+c45sQYqdGR+3c1wXDvMgnc3VB1rsaA4lTNzpaHagf9IvZWQ8gOwQXwqsbklfmIuhMsmnItZUn0e/xIr1NDTEGFeA/msFZ2z9tu+qS4Fy3PR8tl8FPegyn8/OtL8urcPoq2R2/kdy5awqDRKrPUbrTAPWGUORsyFjldz+wwqxM+f/7Mc9yBQq7uMTh/nmC4bxad/Lg7hrzYpl6zurfjhQMqPsTrSTPDFTYobsQJ/+l35GV/aE3ZhSg+nK01OwKBqaReupsOByEuxBYKtpEUrxmfZuFh4+tJyiuGosBd/KHKmlvOtEcd0q33PxyZ5kneNj5KG7Qr1M1cMJ/eYFpi0tnJOTYcQ1IOtrAjUMZkkG3voPvOHrevrQTMENN4958UiegJG8HVDq4rCa5UOXN7H/KPu5teCjCqDla/bwD6SRu8QiDFuPt5mm2ERAa4quGpvZVAcuJSY6bx2n+zt67pthj8QXp+LEnVQY5f3KQSuATNO2TyDehLSz1Al6vTA6PPBEFvoYVL1D1ZONJ8VlN0m3gzp21Z4iRwXSW9MSfVsrmMITp4DIyehqTsWglZRM3120uezo/MksPYmnZRWM5zllYttyhrJs2X/7lZr/XnS0Jg4NTo1DRPtPqlhl7X7oKt4RwEI9tz0AGcbXt/KiI+ejBkLtaYOk2JFOg==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: gitea
