---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: gitea
spec:
  encryptedData:
    password: AgAdy8Tbhn6sMb/atLT/0dTskdCTHoDu4fadcGkdJIq/YWAZ0drZJQ3YYxdeiXrzZUIKB3zYHJzS13KYCPPvLqZTPVAcpzD0jjKQdJGgxXiO097/wv/dczXW+UoK2qWnOSRbW7ynBe1n9+6iKxuoftLJXRS7QGurqhx13M1Yq2TAsIaZU80pC+o8txtHVvY1SGym6uhEaZzKfSADgCUvdjRqh1whkttgZiKugtINHe2KQA/jKNAEAHl97Dd9HuZBDkmIMacvAuzVvRi7cO6YVNKJ2gvUgzMS6AD7GOcvx6tAXo31iMt+YRvdDa6+HmZLit1o0BQQOQYGHNrjvq+JejoQVCHGT9B1FQiE/TvNVsymjMU5Rr/mtgVVBicYoDPBeDaUYZi6TjVMyLp8Uj/R6PoKXaE8pOrOcwvJP3k5b4OH7eY0Z4P6zxczDsSIOWoAWXT9QggMjdSHX91BikEf4N9jgQb6XTe737aJnPP/iV+jD30o320Q4l8GaCkTkHCVP6PadRBFVgK6TYIsr2/gHJTw9C7fLlNw04+bW2z/iOpUgqJh+FHJLRSMNlOVOx36rUWmmJjs5SJawY2XLMzSJ4RTlkU+QXQndd277TTK4TFj9ftKBO7zgVQ7gLh0G5sgCPh7WemGod9zSBkPmqq5JGLr0lBw2qSSxt4271Kg753/mhm0dVmVM6hDKItz3u8iY5idwX9VopM5v+o=
    username: AgAXNimEv5Xy2vfswZdt3IFnskhFir+Bdz1nEljXai9341f7wvVrE9a5CJQTOJbXGlL57bc0RcvLjxDQdFHxNbuVXyr+p51MJ6ejj58HNLo0Qgm3juk5W+dxTfA8LXR709FFLcfyTEowON5JjXwha5jvRhoP0eQ5Btp+osMMT9CiI+Z2LRABDVf6+1RI88LfHLDw4SkguvLu5MERxzmBIE6leJmyXPD6ckCj0p6Ui+2NVB20ubSES7v9a4zzmQ9QJpCFun2ufj98cf4x5Q7CG7nzYq0QyZGEqIVXkKzMRMAwdqkGvtRl535hWZLk67VNhXSKRSfLiYZirMbvb7VECSewQzOkPMKppVJo5AQyRL/3HL7wHhcGLtNzBTwrL77QfQ1BvciSxdSlhu4+fNyiTB8ijHde3b4KmbeNhq/jJzSWHamLlyrDpyeQFsnaFjKQ5U30RNxcQrmgfZI/NXcFynTqJPyrOFgpRSj9kqmELacE8Xba552Z6o1iw3wZqTTuxSruhhA7VP2UZBeU53l8hNte29JWUc0byflEjMCh4Z23f1Yz3X0Ao1Nloixb/wSNM/WiE6Mj0TP98/+6qntRT4gINH3rMxMhW6s4Ip8JhxI5DU0kUaBfwRAK6ndstp1LVkKUfQvk2OReb18+VYrpk1QZuY6tIIX2Y+FqWIhlF+6uhuh1goZ67npl2OvNCRhxfQTy+tYmRw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: gitcred
      namespace: gitea
