apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cluster.gitea.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000