apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/panaxeo/edu_devops.git
    targetRevision: {{ .Values.targetRevision }}
    path: apps/loki
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
