apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  project: default
  source:
    repoURL: https://github.com/panaxeo/edu_devops.git
    targetRevision: {{ .Values.targetRevision }}
    path: apps/shared/overlays/{{ .Values.apps.shared.overlay }}
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true