apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-push-image-template
spec:
  templates:
  - name: build-push-image
    inputs:
      parameters:
      - name: container_tag
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - --context=/mnt/clone/devops-app
      - --destination=pnxedudevops/apps:frontend-latest
      - --destination=pnxedudevops/apps:frontend-{{inputs.parameters.container_tag}}
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
      - name: workdir
        mountPath: /mnt/clone/devops-app