apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: push-changes-template
spec:
  templates:
    - name: push-changes
      inputs:
        parameters:
          - name: container_tag
          - name: destination_repo
      container:
        image: alpine/git
        command: [sh, -c]
        workingDir: /mnt/clone/k8s/base/{{inputs.parameters.destination_repo}}
        args:
          - |
            git config --global user.email "ci-bot@example.com" &&
            git config --global user.name "ci-bot" &&
            git pull &&
            git add devops-app-{{inputs.parameters.destination_repo}}-deployment.yaml &&
            git commit -m "Update image tag to pnxedudevops/apps:{{inputs.parameters.destination_repo}}-{{inputs.parameters.container_tag}}" &&
            git push origin main
        volumeMounts:
          - name: workdir2
            mountPath: /mnt/clone/k8s
