apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: replicalimits.panaxeo.com # Must be in the format <plural>.<group>
spec:
  group: panaxeo.com # API group name
  versions:
    - name: v1 # Version of the custom resource
      served: true # Expose the resource via API server
      storage: true # Marks this version as the storage version
      schema: # Validation schema for custom resources
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxReplicas:
                  type: integer
                  minimum: 1
                  description: "The maximum allowed replicas."
  scope: Namespaced # Namespace-scoped or Cluster-scoped
  names:
    plural: replicalimits # Resource's plural name
    singular: replicalimit # Singular name
    kind: ReplicaLimit # API Kind
    shortNames: # Optional: Short names for kubectl
      - rl
