apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: required-env-label
spec:
  policyName: required-env-label
  validationActions: [Deny]
  matchResources: # does not match cluster scoped resources
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - devops-app
            - ci
            - shared
      # - apiGroups: ["rbac.authorization.k8s.io"]
      #   apiVersions: ["v1"]
      #   operations: ["CREATE", "UPDATE"]
      #   resources: ["clusterroles", "clusterrolebindings"]

      # - apiGroups: ["admissionregistration.k8s.io"]
      #   apiVersions: ["v1"]
      #   operations: ["CREATE", "UPDATE"]
      #   resources: ["validatingwebhookconfigurations"]

      # - apiGroups: ["scheduling.k8s.io"]
      #   apiVersions: ["v1"]
      #   operations: ["CREATE", "UPDATE"]
      #   resources: ["priorityclasses"]

      # - apiGroups: [""]
      #   apiVersions: ["v1"]
      #   operations: ["CREATE", "UPDATE"]
      #   resources: ["persistentvolumes"]
