apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-pipeline-template
  namespace: argo-development
spec:
  entrypoint: ci-pipeline
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
  templates:
    - name: ci-pipeline
      inputs:
        parameters:
          - name: container_tag
          - name: app-repository
      dag:
        tasks:
          - name: clone-repo
            arguments:
              parameters:
                - name: app-repository
                  value: "{{inputs.parameters.app-repository}}"
            templateRef:
              name: clone-repo-template
              template: clone-repo
          
          # frontend part
          - name: frontend-app-ci-pipeline
            arguments:
              parameters:
              - name: container_tag
                value: "{{inputs.parameters.container_tag}}"
            templateRef:
              name: frontend-app-ci-pipeline-template
              template: frontend-app-ci-pipeline
            depends: "clone-repo.Succeeded"
            when: "{{=inputs.parameters['app-repository'] == 'frontend-devops-app'}}"

          # backend part
          - name: backend-app-ci-pipeline
            arguments:
              parameters:
              - name: container_tag
                value: "{{inputs.parameters.container_tag}}"
            templateRef:
              name: backend-app-ci-pipeline-template
              template: backend-app-ci-pipeline
            depends: "clone-repo.Succeeded"
            when: "{{=inputs.parameters['app-repository'] == 'backend-devops-app'}}"

          # remove old images from docker hub
          - name: autoremove-old-images
            arguments:
              parameters:
              - name: repo_type
                value: app-repository
            templateRef:
              name: autoremove-old-images-
              template: autoremove-old-images
            depends: "frontend-app-ci-pipeline.Succeeded || backend-app-ci-pipeline.Succeeded"