apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-pipeline-template
  namespace: argo-development
spec:
  entrypoint: ci-pipeline
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
  templates:
    - name: ci-pipeline
      dag:
        tasks:
          - name: clone-repo
            templateRef:
              name: clone-repo-template
              template: clone-repo
          - name: npm-install
            templateRef:
              name: npm-install-template
              template: npm-install
            dependencies: [clone-repo]
          - name: npm-build
            templateRef:
              name: npm-build-template
              template: npm-build
            dependencies: [npm-install]
          - name: npm-lint
            templateRef:
              name: npm-lint-template
              template: npm-lint
            dependencies: [npm-install]
          - name: npm-test
            templateRef:
              name: npm-test-template
              template: npm-test
            dependencies: [npm-install]
          - name: build-push-image
            templateRef:
              name: build-push-image-template
              template: build-push-image
            dependencies: [npm-build, npm-lint, npm-test]