apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource
  namespace: argo-development
spec:
  ports:
  - port: 12000
    targetPort: 12000
  selector:
    eventsource-name: webhook