apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: frontend-app-ci-pipeline-template
  namespace: argo-development
spec:
  entrypoint: frontend-app-ci-pipeline
  templates:
    - name: frontend-app-ci-pipeline
      inputs:
        parameters:
          - name: container_tag
      dag:
        tasks:
          - name: npm-install
            templateRef:
              name: npm-install-template
              template: npm-install
          - name: npm-build
            templateRef:
              name: npm-build-template
              template: npm-build
            depends: "npm-install"
          - name: npm-lint
            templateRef:
              name: npm-lint-template
              template: npm-lint
            depends: "npm-install"
          - name: npm-test
            templateRef:
              name: npm-test-template
              template: npm-test
            depends: "npm-install"
          
          # final image push
          - name: build-push-image
            arguments:
              parameters:
              - name: container_tag
                value: "{{inputs.parameters.container_tag}}"
              - name: repo_type
                value: "frontend"
            templateRef:
              name: build-push-image-template
              template: build-push-image
            depends: "npm-build && npm-lint && npm-test"