apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: npm-test-template
  namespace: argo-development
spec:
  templates:
  - name: npm-test
    container:
      image: node
      command: [npm, test]
      workingDir: /mnt/clone
      volumeMounts:
      - name: workdir
        mountPath: /mnt/clone
      env: 
      # By default npm test runs the watcher with interactive CLI.
      # However, you can force it to run tests once and finish the process by setting an environment variable called CI.
      - name: CI
        value: "true"