apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicyBinding
      name: deny-node-port
    path: vap-binding-warn-patch.yaml
