apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress-route.yaml
patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
   path: argo-server-patch.yaml