apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
- ../../base
- service-account.yaml
- deployment.yaml
- loadbalancer.yaml
- dashboard-service.yaml
- ingress-route.yaml