apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: app
spec:
  template:
    serviceAccountName: argo-events
  resource:
    app:
      namespace: devops-app
      group: apps
      version: v1
      resource: replicasets
      eventTypes:
        - ADD
      filter:
        afterStart: true