apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitcred
  namespace: ci
spec:
  encryptedData:
    password: AgAxk6oh8jG9X7PbB59cgPqbQWlj8nxO/bQOJPd1lWR9cM2JeCtHXI82DEYp1LTV3Ys5y+9R8wZDPUVpkHDCqMmLG5VUCDTh8j2JOZFhjQZNJh/5f7Gr53cz0Qgi2yGp3CNIz7sQRppWEP7Z4YhamSpkYW64Pictz88lw4peh+N0TAKak642oBhXiUuP48znVPfqjuwf9vJOtkhLx6UPTIGLPsLhmryzLSrvEAWhocjEg28lA4z+NBIgscLq9P+txduxo/rRe7O6lQixME3TVImYdwz+bWAVlSfclCdRFpUdoy+InX/eX3BLXgkTsffTRg1bOLk6Wl70DmS9JMzEoisGYjiWow1KW9InQ79NWmTmUW1IW9/qoAgdyd9b3uAq1HkyqNCxRqcRrUUB/2afjNaXpkeNiv+0iXNfR5xfvga/V+gtRmLdbgqw7BTwaEVRMswSeiMzTuMwdIsjNEgVKPleqBf50fjkjuba9Sk+ThVCJWFc4JZo/JUhdyv08mGcqasbqCozRHE6yn9GXf6ufIb8+T23JwhWch1eiHlMun09CeyOFY9+plb7mndSYkMuqe6N0RtBYMo/8G07KauFMCVxuy4QxY2W7a+VJiKMne4FyRkHZMlZjMAkePh9eIF5kXCDDYbnRl9Mc+FCxrfzRRIX2Ln+uX4wOGOP5oCIk9y7E4NVrNZGfEd43qlhQ1eX01g5GGS21tCA85o=
    username: AgCrNf+lGuptqTZTnhEoA9q5M3YkDdNLkWFuiRwYZvSUjIkC2P9nLr/Sy3722hIyuC4S88UWLplspIybY+hP7aI2ehtGoIy95jnJcND0J+XZM8Z6won3vYg8PLUZn00JZrwQRimvUTekzhoAu+VLg2ASY1GwzfZYWqeO+Rr8Qs6MkKhQTCztTxW0/gBKMLom5hijhf9l3xeT2wq1J/xxcllslEb+uZlzVPo2QoIUnX2BV/0ztkkRQrAWTXFLJ4Vl1l1P+GusApUJd5Ee+uxXYwsWyOjaQgoQ6uuaLXjxXJFZXIjiFveLixu/1t1ifuMjGi6RzV5f51YPJSgM9VyPhJ6vY4+QEB2ixRy8E9HHuhR1ShHeWLZDQw6cKpd0j5MVxEqPO4WtfU5fW66saGvqIdJXw8cN5aw9H6vlDB/YS3yHZsUZFvFEIA69Wdzm+P3MyrCQ4A5K6S3By/xz7RUpiDL4Gtr9K0LBTb8pNHdOfwWTnvNtkRZpL9UdN3jYhLqUlZteMPv9jOxP6U2zQLVIZDWVA30J9WWHjQd4+q+wbVSCFBQsB7g5U/V+5gsvGOu44wVbpJiYn6yGNN8BYpKcUf+KZ6OyredOJAtDt/Xuk4g3qC0W9dcxHfTHsfpoHcGAd3KzExSFKaOW3zWkX1S4dzfd2sFfwGwRwHR5LP+HeQHLMRkwIvYT9F4zZgw0ACwQtapqfe/F6Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitcred
      namespace: ci