apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAUas1njlfZ9Eq/vGAQ2gngj3bF1/VupoYHycSwSuacjxcoGYIhopyYeeyuJAhZNY5hDIqwrGCFWg+v98Jj9HPIQ209bZUTxSzCAUHjMoReuh9Fe6HIxmm2OaLE0UKz6kaWWpmpWVY4ShknDMqu68id7MpoOT9U7ICWtP5EK/TRipiVtjcoj8x98ZqNUNhT5gbWQP8fgBG6PmIMEYyY6SS4ZnxSx0bs3GcbeS9aJkclm2tGykKI6NQD+M9D2ZDCLqM+RsCH9KoWtHI1SUf4FXPe761OlxsbY8d0Zwc56d7KUu53mTE/+2oc1tM3cyVB4t4kjerj23V/TFG3MSiM65cxw7Yq27qzP7oVcVt9RJfmbtGBt0Lz17QQCmqHutJAcbCAdglhvNoMdC/dp/xRTYJjaQOye/mGTkQ2tNLSCwLno2P8Okc40ock3g32bzRwrfAD0ahABddJvfepqTOA+RHqrc5xxjnERJpckmB8z4d/Q/dh5DLfAuLuOygTLnp9faHDdepU9i+6kV0aBwCxSYRo5zwotn2qZXVc1STMfuLdGIVX0mEnkANtOevtZpWlVQeNq2F0WfM/tGRCUmkmRB2Tj3yCQ4pcu85CKqlcQC8Sqr/mIIHVFXR1iIlC5KRDPpGGxYUNOhIxAHwnRpeORlO66w22tpql9w1ww/XfHMMfA0Y46zfUiS8rqKXwvag1TWNfrkK5pSf7F9Rb1t+bksYW9yo2KdPO4PIyBZJ1ShVfXTx258yEo8zZuCuNp+VA5s4dUF4xdMSJWENC4pkT0GtXqPmEhD4xBFhz9RnSziHFbl76hlRpT5EXHGR0Wvb9h7LcsRFmz4ENOmxRgiggO9B3UJ5tcxntmYlAZw990w1QWCahCjMbDCq1H9aMG8CHHFIrrDmoM4CdMem/CXYXy+bpqNDKpYuMR3FP4g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ci
    type: kubernetes.io/dockerconfigjson