apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prod
resources:
- frontend
- backend
- regcred.yaml
- validating-admission-policies/replica-limit.yaml
- validating-admission-policies/max-replicas.yaml
- validating-admission-policies/max-replicas-binding.yaml
