apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend
- backend
- regcred.yaml
- shared/replica-limit.yaml
- shared/max-replicas.yaml
- shared/max-replicas-binding.yaml