---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgAN00eC1cBdL0adaiRo1wTKKN5ah/jb4zFoMRqLBgggWJQvMa7YDxjcM38MhVROv62vJYTPX3zdB0SER2jIBS8VmJB0/wvMUiak8a9ChF4P3FoJTy90Y+QA1lId0IPyWc/kNrLcJAQP9EmZ3Dol2HkiPxfw+8gCUfdl1cgCkjSA4gZbm3uXesR1ae57w6d5bPWPfFsDmaSqaH4OxVpgdY4Bn5PSOMdvNxM4Mzj5BOkuHtJdPDEsWy9iWBIQzFzhpBc9bCtzVKHFd4zZUmb/GPhbGW21TE22xrWEh9Az/hTMsm7EzSVZAICKrySl+uNsBzisKJYixEAcbxD2tUmliqzn+8oSTDbwfT0cInv6ZIRjHeb4ypHZQGPrvURovF+CeOLXCierPUbbyb1N4TVgT+uGkunORxa/wg0E6jpCgtsjQDu3R8ojwZsUYs1eNJMNkmQeCf0QkhgVvM3pY18rS47J7sVnNaSxb8JimhGYHkbYyrf7x7kVYXEQ2mEEm5GsPH22L4BvouhgImY+0AmTKufENtAVtdFFeuB0G49+A+HlGTzmJjWv2ZQLmbSXxLOk+0xSGTClAAg/Z3khDxS8RaBTj1GcgRh9rrZy9muT54d7QxiIRkHmA5W0BeB4/9AwcYI4w5hfFIrO18Q+sPmuqPFA3RpU+bCiNEpWf5K3cC//IUc1xTY46HFZFlGDD6HPFgLbapsgBbh/F9Snawnxqpy+cJeS+rCCjY3CYqg++SO3wumlC2xa2fSLcfoN8E5XVjk49wMZcjPmJ7cyHMqsBwVLhvfLXmoawDfFKQF92qWcfOV5F+rDTT481OSqFBzdayIgSM1Drd8u/vFKOmgLXrK9b5IccQJLl/D0uP9kw6oaWDG8hl+hoNjdyxr7FMEV4yl6DfrueZdupiuxXUzM2rr703MGjeOMO7Vp4w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
