---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgDCgmkqSZFyZ2JmETtOL9KkscoAaBrqrGj8/YfS7RLf4OQtRNRzKFTUbGfLn5KOG4FsmprjjusPQvB9O7xU4a0VfIvEB1J84T62cUH+ROGKuCF0oKXDAPA2HK20Oxq2Us1lgufcz+9RSkPHLQKqUryn2tIykXT9hq+O1cbbDBLO3QzTI/1+prQ1xA2aNOCsbDoiEK+zhpR+m1xzOu0jcIzDy56cPT/jd2vISUTZYAlHtxfZfUUmSEGbPfuteLCLmKwxMoLW9O/qkDLj37a0M4IFIm6Lt/GRP7+Qd0OTxCUT2y2ZodJ9rU+C6ieqcv866EBFXDUzBuioysQH0dcPhGt3EWtdI7U4gQglmjp61OIUgX04JD5aWknVXafA7P/4dgEj/usyqeiE4JNi9jD0uDMRhYU8tf1Nl0HNXOJ/Qtt+WOOW+RN7efVNFbzniWv3kn53+hr0zyxVO3lIucfvjpKjkXvbDfRMep+P0a4wPkN1WbBSljihDMX0ZsfMcQ6km7+BvMEcmR8h75WnnLvaqirx7PWyjeRm6IrRZNgQS+ZYDKMTJJWcFp1kfPtsG33Ie/FPXfDn3CYiRoRB9GFyxWGj+o0Jxf2xWg++EcE7afHQicaZ5NcAeY+BC0BO+JOs/C4Ew6RhVc8EdbU8cGR3SoYSieEKakab8hPnl9l0RCobBoTGUedKQA/GBYaCwqlXKi+D0KJfZRNq4cN8WSDhBLHRVPwG7L3Lm4IZnYt8xRblqRjcbsLd1bJIrLecj1SthCJyvegqJAloniK6MwGYRpWOnE9BPIrcURXG8hx07nT+YN5BgouCyLVQWZ1aytvw0LJCtw9na4Zxqnp8cXGFDPvBHHtVobS3xO+WUmR32vzCoyL2/qkK9408c7AGWQ+hPoANGGs+lXZA79BR1mlLou04/liCazK3XTCmNw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
