---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgBAjxLioK0Qcr131BitWkvKFvAJgY3RX08WcGBaW5MW/TfTskyum30jCdEwSDOOAZccKVS20MKXk0A36LDVbHewOXWn9KSzluSZ5uTb5O3nl8gVQJvsAf6vFYertFn5nZ4rHGC/gfdCTwmIwTb2vRrauOSdD3L6uMfV3l/3O1GuTDwNy52vHeRmnNc34nQwvcKdBZdUFdnU/gp32g01L9MCH/fB7Vf6zwt45xCJPzXje1aw6pB4UQQ9QYkgB8KqvDVwJmZreaJqTJvRBDyGnWGLN71XXAljL2snyiV54Qlokj7xNAGVGi9oh6Rxo0H1zruda4r0SvJYeRTLIsR3/XSV9dCG48aaDlcXhFBi2jQ/G79QQ2YlmdeFUKPP+sWj/x0WoM1PdfWOOtwGJtwaj9bdU8KCMtDtiaQZG3LMCCP8tkMFNUfOZJT8wqtBLkD+klxJxQOHL36QEnAUxS032xzeZm5VUMHxOnuLncBcSBYZqwNX1Jtoa+NJeZo1rFpw3q20nP0SuYOB8VBjR4FUrOYe2mzG1NQxs1KTgpeOSWu7bpvI+w4grwq24ZdPd4GsGXNKkgGkvzYBnr3kwg4RuFBNQNNQVd7on/axz43pMolf31IfTu/lducxK/mH/QrmOvpCeaKXaV15DV+phCIM51AYQurDPuiQsHBr5f8EvYHiurVlx85/ev3uvmEPoFbaZg45dvq0WFFcpSxbatWJgR8tHvNpbKtjWiqAw+xPLANbx70/PFHXOZYJM8oTUQfqWd2bnidc9ODRvgjiRchr4pu+wRJJww/wnzkQYqGjGulVDIkwgXs5HHTnjKoyCwp4/RDpmDhGrCv2iLGEL7gudnwIga5RsLEuHXlVhBq85slNcKfUSGYrKNL4uFBNFGljasQBg4NrNf9RoX9LUljt583JnxbWn8Hwuf7mmA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
