---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgBLPzXAm5pt4acUadiXm6yi+L3b+i9ZxuOHztcKZgfNh19hNmGtZf5AN2a7sUJ6GNeIu2Bui+gh+v/19pcj7zqTRSE5FfPftrpC/tFuu5GAgAbHywZVSPNAB+PgR3AMYjY4j//hL9L03StO3c+a10FAHibMfvbjJO4jF8TrJ1YRHh9x13Zrd8Rh4WnVTWpcAc5C5MaQS9757p1B0ammRsXIWKp+AXc7zincHsjFardU/azJI8sQ9c82Dj23qLFs53URqPr5zp/tNcQDHngqrEhzpCdnu93cbhxCuzkh4v4bS2rdBrX20aWUqAxAhgsV3ouLICAz6UHpZzRj6FMbwjfN5p6Mg6ppF+R1pF1cQEmLQsdIlsyR2JIgwukIU9+XbqbOaZVj2SS0JRKwNe6mupGF3YTgZLxkfvHk2G69UiJzG3q3ez8ooF71Qq3iHiaPCYgGk3jL8K+T8PQNU5NsvDMTaX65LkfZeA3kh05r9kd5h3WtMeQeCQSbHHslvSCcIq6C0x5a3MoamSzGPN83BL9jyGQxuBJ4I6sOBrQabvGW8iw8evT0NU2qGnX5zRuaZFM7RVUJyvAqjrzraWvwF0WVTqEnxwMhVhRvIhMX6T3Majpv+UI+gO492p79UHel36Zz4uiGB3+mxKYPwJp6UI4L2NhSMq58oM70vIYQzjbcVzoi3FeFa3dRqIwbD5Q24UbicRhBVfxRHf6Yb1wfkCYmDQRmw//9v955SDXQNWNgzqxRSS9Ey6MSES3Cn+F7llPoWa+n07HK4vTqGiGpn16MMpli/oeIdn8IWiayTlN8T9xmGh46jzGv6J9pcl1XYz1bbimCWwh2MCRZKYdEgNS5/leIO1bvfWAflvHm1AQBuXscrOcHkWPS5cHGHVlX8Oz11aOaE1FTnj7nfnCFSgJAq1cwWyWkEr/Dug==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
