---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgCC6VKsUMJj+ExfNGvN9aWwkl8SyQmE+q4EwA05jK8JvmukCbH7NvS9/+FyH0XJD4PU9JSD/kjaWz7+M6Ze0DFvys29ULN220o9tQZBJoCTIr4g1NmwA1601tgNO+g0c4n1GCNaHyNMZjn/g5o5U7SFhuWvrkbLrhT3j1+5plBQ+puwh7b9WPq3oXmqGSSREF1WOsP74JqUiaworaM/Jlr6MQWKcbNBJ5zhqMgghkCVqzggERHwMDK6Uldq9ytoVyrYQbuugFesuKOO40feDdo7G3s+tT4BeB64zR6zpUhAuNNORybK2uDVYFGq2x6PW77t53PYZ1VjgopcxxWgy96RWftfjq1wHOOXUXDw7XHg3Zk/dfkau0UPw8kCANuNo+6uNku/orjtygKYsORYibvn9q2lBHsxpS1oZatioKn5o29UORQM8qzBIque+tqE4tJjOAHtk1fl4q7GAr0WIf6I1NVNkFEDwsLoHM2Qic409XGgxgxr8AnPzgP+gp1DZ3X/kqPVAlrBchGIdrlJupJqjdur99sNynMwoZtRtofSXN1Iocy/6rwU9HlfxeYfaI75zc4EMcu1J2C+wJcULu9vZutrnVS+bgiX8AjdhFScguPmd7Z8r+Y9GDGm421cE9f9Jz0TK7x06qRKLPMU8VWlTSBOOu3m+V3ZEX0M3vlCjLsxZdG+9cVLNF25ei3xCPjG6cZaFbkC2i1G9/X+dFAG2UReYNxKhfVVYJbU+oWEjRZzRaDWfhBcbdqKi5Ljaem8gQO9RVpIUdQq1/hm/SUzrstznuY3nxxERmc95R+7JTmVR0XeqR4ZRS4lKLBZgptu0D8cE2uvQwfwILoJ6IvmQQwA5Jhc0J7X8Qkvd+iwe0LlKiOF4jjEOTDZSB6gqMXjD8KSf4nLLL9Ksq/GRRnBeRAzbOyBtvkxqQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
