---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgCq+ORVfLpZaR/d6tBjetVYGuPxwiifn3WQ2UGgTyaBkowzhneyeyOkHlFlRu0zs+qkArj5mrJrLO9eAXK6v3IWfiOfWDbTKicta4cifOgbvg/PjD5Ydq1P72eRkx4oF13b2YGVt+Wjz6/epywHvKAi1qGDwJZyfjsKTdOdORueHlfrbCmpsbYFTLaw4hoqMAa7PS5tuqHOIvYu82POW/xmsUVWaGJ8SXFfunOBRuq6fgEWuXYpl9WU1gVT+eitVRn/pVV3z2F4qOygVdS7UwWFujfO99UZrjMDS2VkmIJoIW1a6zHdn/wKKprP4SbnQr2583Yj4YViaK8u3o1Q9kvyBBtHHwn/g5rzSoLhiginsjcB5gFlMozFnnReqkD/DYF3O0ppsdZAiglRmrJruXnRnidAtwONXzbFdPJgm24kT92cMNULkLUTATNFrv5oXj+/8o5tLuTvEraLtoY5eneZUBIE2FBG6meG4IvcVPIhK9flkRvCiRmpVwHcWuFcs8jr76fwvPbX+It9VHJYeCSfPKKS02VyA98xYu1nZvwuF3qr/2sSHlOgsrsq9Ctxb4f734IpEZnd72z6/36/r0VQ7Y25e4b2kIUWxjTlxo1JfmaN15NqRS8Q1YinujiLssqtUsNl3PmdXZM3NNGMZYCjDi0lp9/G++/fKxC/DJ4Ra0RCWR/w7m5nuOfs3cXQe5Flv0dO2x+ztdfgZIGdKRPI4eFGGYsrOcp7mVSEBDV4ZQ+uFdMs0zBxbiSbNt/CcxsQB4XIT0lcwNRIVeeRs+OLxP8peXZzKDo5+Y2kYwQ9FWMCYT78NudKtORb3XFgR7K+mtxy2/g27T6m4gcyza78YlgU5z70V2AFy5+bNS1/qTNi7kbqr80RIObAcyhw/KpBxRVueTAwM/0xgqUCgz4T8FFjjINPUIXWEg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
