---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgBmFKH7uWGgZjY8LvspN3lBcnXgyWpNLLKuqhqGTecyUwJCXz5pnObnV5rmImL1l+mpQ1rm/gIUlOHdqXQJQte1ZFiOJUcIbpdW9lwRAkbE+Al3qLazBA3i8lwOEk5osO9cC5qu61tKp/HCdVK6khOXK7hCGoBFQBBkmc+DTAmlWXLcP/9/6cPu4e+6rV3nVjNDt1p1D639DQnp0+zYOuytXfOXjFQePz3zMmKFIdLr94k4i9VKuWBu5k8/YrPUJ4qfU2mAgUs/LG5k1yL+TqSNFEE9UIHKz1TZ46tfAbu8fE9RJPgYwkGFGruKSu5IjUVbvLFrqqrjEAUWn6dzlvwhPy13Dkk+9qtFJPxjHIrik32Qkttq+jDw2zU28jehJCf3EdESINI0IDLHHfmJxv7VkrHnb4kw2Nq7/cl7kyRy2dYYTx3iiJGzQ3ejtndqeaJxxsVxBeu33nlbR2J21c8bL5aXWm4R+ogG3Ox7bmeS466VXCEMa9iAA3rQ8K0Ou8ctBrCDi+61uoR44x8yFaf4GDSVZQF0lT5uYgTxF1FD4/kpkV5uokoiJF5m2v7CjNOXWQIQCmDrs7OAL+CAi1csYf4GrJzd/uPGNo5rM8qYZ3niuj4qwifUcv/fAAf9uOpnqzHX9begx6in0E9c6wp+9IwE2QX4/zNwoS9GF3acI02k6eKL/vhLuDR/pRljixnOpNdiHHf+y830SU+zwm3IyQm2MdQ1kH5xuoTxb5iG+xeX0DJBolljiKNlUsNPi1LAItdvYmsZnt6rmgtxyRbnIoupRQ0LR8vVlf8kknSzYdf7wmGkYp9ki7IBHAOa9L85Zo+GdXq40rH3qIereqcot75Bf5DGdewKWe6ApQTPfDPouB15JNRwMmwEizs3wC6T7kQtGg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
