---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgA2ZYlH0/E64WVIWtrrT6VBzMjRbYGke0VqHBdEeGtStaETNWJqtVVwYsdQnLLM3Vas7rMJSMleWj7rqW0eBzoS7xw1h5F19s/2Xu2uYe8GNv+I6RAMJWUdk/uDsdih1GA15FCik6bXVQTOf0uB80r7J1sO4VyCFcUa2vL1oupkb1BXutcoyVkJcId6WmblX7aquadqhMP5P0rBUWdiVPXVbvo9X2NeNkEjBoss30/Apc8PTyb3OBo73cQixZ9i3q8z2bzLVU9L1MZY8S5arR3s/CsUV7AaFrLuRELvSBvYSNsvs3I9HXxDnM++lA4fYTS9PnJ1qmPBE4KaqghBNIRzX6FU1GC5awPECksTVYlIxgcKYttJQwq9h8e0htjlpSBqKfUlMFBhpaZ2cWxKx3AI1Aq0gddipLbvhFH7IRhuA3iwaeddS2nsDYT+Hue41KFrJAae3jSGJJqkYTz5iVIIQEDlooUxdLgzhlkhYV+1KngFB9tPnWxbwCx1dehOtQppihmxnQIVHVG7lLjkznLuXS/xsnT1VI6B1TFWUrg3pS22U6kCr3vKC9Ep0D8ro88Rj7NLWUt3RHkXAgwRxzMaczaF5MD0wWHMYL9RVe5UDjJvfiodbYSdbhPvvzsdQrmu4y7l6E6PlhdzwuOJJ2lMIYJPW3WkGBFGHFz/mjRHGFCiUCF29YTr6lbwxdm1ho+oJJJmW3EAbVby9tvqF1fgMhCvJ8SmMiU7xl7NCBqxwNswrtzHplF87KlyeyeyTx6RA8R3typVww6Y+w3/7bGKIKxz2zJI8rOCGwUML9K7LN1iPH0wXSmjs0Bk5UiudlFsSXuTv9giL/xWjIa3Y7DYVJrbHzO2OnnE85a8fe0G8ShlIF9UkkwfiTFFWI7lN0dCAlLvRmc4o1x7kbT7GeZoETsdyQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
