---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgC7QXXkIBb9anOtoMMG5/OG9Sw2svy92EcMXuMjzUQ5dKrsn2RAjLAlhV76nOeh6mFcNhJRGqXqg48rW9m/NoPTBC9a7X/nR7AoRiv4hdEQF7awmzve59dFPy7ydzl5cmVy04sWsytCT8j8uVNY4N73yjpOamFqAuULXLqHxUOGQvrqNg4+yVPkOlM2UQ+JYbSh/7l6fu2gUIM2Iio42Arlx04jyPsP+Vhc3q0v7OqkjrD16t3wtTESkHVDkk1ALZpGOLFiSrrL5oKehzOjeRXOw8ZWGCvszAjJE8SMkqADZw2pAOc1/z7Mpo9QXgCXP7tzSC4N7PjPs8j6JoGWTPmpQ2xl8nrBvbgGTOUoR2DXiFgL2mkCGwTc4wMRbLRWseO/MKBpcB0ie4Hx63GhOViWa7RZg6EKH0uwnZS/MjIWt0TX3/Z62lpbPmkM+MTE2Gxpoxz7hUl6WrdJVeiU/UHzdB1kGAnXWO91JdPQizZlnoEQ9EGYj3vJ5IPU4XQfhIKUtieuvoPCmue78GWkiYRNppFEmJ8d13sCXHC+4fthe4uZB7yGRdOi3Ao0Dunw2xSnGJY13jhkJ9yxxvtf4tEYGcfaOufDoawnH5ckRqi8UybxXaUhA3f1QZZNB16q7P8nZ59Y70eDmL8tkIV26BG6D7CFrhydW0sfU1cV9WGNY3xnKohHri+GfBGdIv6bU32id3JlQgAhAY49GfUTIcUOV4ujdkv4u3jJ1jjw9eT7WkxZwp2FEsNGbESlwxw7tD1KOE8InJJZzPke23aAHhfQvwBWmm8tNPTWlHdi4X0clvSm8yx9Xmmar93cAnn99tOLSAtLc5JnDGdgrm4zK8Nig5UhhVVbg9nuNoEZvZQYl5yxTqsqiGYF4GUdh14YRMHSE+toLsKI3FmYSBywL1mu9ZezCmVSL8d+3Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
