---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgBgbIVim43ZE5nnYycBalm2GRRwvyX9GzVY89ExOCGknPsSrlpT/4yaxwkcly3DCsjyh1wHQCih7AtlLqWUJWLOgY0Zhl56V/nF0ERFX2rAjv88JoxVTQRayZP+WUstY4pxXr/AwSGeU3SKLmmYGXn6NIg9zl6IQDhSdaMyxdxamR6L3mVFdDwLUEyYINoUAPbUXTHEE+9d14muf/4nIb/QHGmrkyofuJQHNILZHjbq7rLICyharikDafsdfxQcWWGzK2t6HlaANDLvRpGPOJnCJti5mJIU4gG88NqhprnVvwJ5ckUVz7WiW1AYv/qSweC7QbX3qDuZs/I/iZ4uucqZG83DJkaN0FmJBT/zWXc4g2Ogo3ahigF6I676pqt8Gzexdzz5ocJqzEvjRn2vOVGSMd86dUmwga0WwWlCU/czBKszemc9/9sNUwZ70JMsNDkDXtiQhxnLiKbMWArTP3/rVzB050i5yLH+ZorLQXB4vu64DQJwYZbBelxyZMeRXUh+/2pJE3K/oDfzHl2McYufeqinlYpLVIs0kcneDxPZ/vgHz6YaCTcY3CTtEnRoJldkVcBvAiFzP03Dx/mcpuO/ydVRWn2PImplBantkodWBS8RQQ5hYf7wJpu+0wUiMO9IGnSaLOZTGvpg7DsTRffelicb7RIyaPzA6qaltFGQd9GoDFQbQbucxy+ItmrHTL1Ch/z2BxWaaO6zS8ZbmH2I3n8joi+6U9jtsq6FtNpnozQpqq4f5gAQ60F2KnpQDG8hdz7zQJOAOmBYUkQcl7hh0fbWzgB8px6qKWpcBePxegmzID9tdZgtjEAaa9oX3auFcR4tGXGyjc6+5DZ+sYolkBw1AVop0HhIEk8iTkHr0ePP93Kp0s3emf7H3SHJwIeQ3cvU8yRGIRZYnSetFvIWg5lO/lVbGpTOog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      labels:
        env: dev
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
