---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: devops-app
spec:
  encryptedData:
    .dockerconfigjson: AgA+9gZKu1FycznbCtcVO1gXn1Pc3Xy9p6t0UURHA4A08tODOBRF6S8AN6FkTKdLkvroenX7ItOnmdzaD1P9wKNhKh5ofDrfOvDafxdmaHT8ylkB2bChWj6kPnBVcUWLrEMwFIqkpq+yYYA1dJnYjMvoZ/Q5UeU6yZxxRGuV68X3ONkIw4MQvf8KOy/bweF9MfsuTG2kXCL1PqVy2nrU/WhcsJu2aYPEJXIdjis3o5e9GDggw8s1BMq24NSeEjWEi4pSUhNmTQh9nHi4H2EjhKMXNbYmXqCBOGReshW5fUeQhGqu4fY5VGQdwYRvYN1Ug1V3PM0yK+og26YbREhnFq+fXM8nsptAxhhd2isZW7nIqpMRDJxMiqpOGI4OYV/JYjtYDzBGoEX8LhFgQ0ZBR6DLCb0dPDeLpupyofl4XLPd9onYMAjo5xcNkYrgScu1sMcjzYL+mF+1sDGj7Yn1CkWDmAeeUgootWrmhKutvxPA9UWdtmcFyvtlp9evxKTytb0P9xDzyeJOjY7gvYuuRRXB2Ln08YYas+1LltCZjMLDzEP6X46wCiZzUXe2Td9+XdRBBM60vtvOdEz0x3bz10x87NilItlvdm60W8zE0aDiAR3IDqxTX6oKlNVMeufmnhR6YsOQaWFlGMQjMCO/0veL2wmZF3WKu6TQFnibxcApZ33GhW1lKd1KLWY50sEttfdrP1LdsieMaOmV/+sywbY3mfgmmPmMI5mKKYUaHX+kQP19ltMNVuJSKYOO4qNusKGeTOefLgJokDkvGaFz6o8gljZK59qOUYhRcLQU4TGM1TYJ4LHa/jU+dnHMvBRdFoDhF0jX91HzA5WhJ7WEV6vaXI4UJm/sHR8eN1SdkC36uT7e7to0JuHmGDv+55j/VgKKNDcY5zrXlr92YIK9nVhiDQ8r2XxpoCqI+A==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: devops-app
    type: kubernetes.io/dockerconfigjson
