gitea:
  postgresql:
    enabled: true
    primary:
      persistence:
        size: 1Gi
  postgresql-ha:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
  service:
    http:
      type: ClusterIP
      port: 3000
  gitea:
    additionalConfigSources:
      - configMap:
          name: gitea-app-ini-plaintext
    admin:
      existingSecret: gitcred